### ISSUE TITLE
Typescript definitions not up-to-date?

### ISSUE THREAD

**Issue by rolandoldengarm** [shlomiassaf/angular2-modal#105]
![image](https://cloud.githubusercontent.com/assets/14539000/15702317/76d8a4b4-2833-11e6-8131-d0db33cae8d8.png)
If I try to copy/paste the code from the code generator, it won't build as there is no definition for .size(), .isBlocking(), etc. on alert()

So this just won't work:
````
modal.alert()
    .size('sm')
    .isBlocking(true)
    .showClose(true)
    .keyboard(27)
    .title('Hello World')
    .body('A Customized Modal')
    .open();
````

**Comment by rolandoldengarm** [comment]
This works:

````
var alert = this._modal.alert();
              (<any> alert)
                .size('sm')
                .isBlocking(true)
                .showClose(true)
                .keyboard(27)
                .title('Hello World')
                .body('A Customized Modal')
                .open();
````

**Comment by shlomiassaf** [comment]
No, it's fine.

You are using the wrong type annotation in the constructor.

Make sure you import the right `Modal`, which is to import the modal from the plugin and not from `angular2-modal`. e.g: `import { Modal } from `angular2-modal/plugins/vex`

**Comment by shlomiassaf** [comment]
Also, TSD's are generated automatically with every build so the can't go "out of date" since they reflect the state of the JS files they are with.

What you refer to is ambient files created for non TS projects which are totally different.

**Comment by rolandoldengarm** [comment]
Ah, sorry! I'm still thinking about ambient TSD's yes. 

It's working now.... :+1:
