### ISSUE TITLE
Get result of an input text into the modal

### ISSUE THREAD

**Issue by RaviNags** [shlomiassaf/angular2-modal#106]
Hi,

I'm trying to get the result of an input text in the modal. How can i do that ? 

> let dialog = this.modal.confirm()
>             .title('Create application')
>             .body(`<label>Name</label>
>                        <input class="form-control" type="text" #answer autofocus>`
>              )
>             .okBtn('Save')
>             .cancelBtn('Cancel')
>             .open()
>             .catch(
>                 err => alert("ERROR")) // catch error not related to the result (modal open...)
>             .then(
>                 dialog => dialog.result) // dialog has more properties,lets just return the promise for a result. 
>             .then(
>                 result => {
>                     alert("SAVED")
>                 })
>             .catch(
>                 err => alert("CANCELED"));

Thank you for your help 👍

**Comment by shlomiassaf** [comment]
Hi,

In Angular, HTML has to be compiled.
The `body` property is only for static non-compiled HTML.

To use a compiled HTML you would need to provide a component.

**Comment by RaviNags** [comment]
Hi, thank you for your answer. 

You mean something like this:

modal component : 

```
import {Component} from '@angular/core';
import {ModalComponent} from 'angular2-modal/models/tokens'
import {TwoButtonPreset} from 'angular2-modal/plugins/bootstrap/index';
import {DialogRef} from 'angular2-modal/models/dialog-ref'

@Component({
	selector: 'modal-test',
    template: '<h1> Test MODAL </h1',

})
export class TestModal implements ModalComponent<TwoButtonPreset>{

	dialog: DialogRef<TwoButtonPreset>;

}
```

modal call : 

```
let dialog = this.modal.confirm()
            .title('Supprimer URL')
            .component(TestModal)
            .okBtn('Oui')
            .cancelBtn('Non')
            .open()
            .catch(
                err => alert("ERROR"))
            .then(
                dialog => dialog.result)
            .then(
                result => {
                    // sucess action
                })
            .catch(
                err => alert("CANCELED"));
```

Am i right ? 

But when i compiled, i had this error:

> Argument of type 'typeof TestModal' is not assignable to parameter of type 'ModalComponent<TwoButtonPreset>'.
>   Property 'dialog' is missing in type 'typeof TestModal'.

Do you have an example of using component on your modal ? 

Thanks 👍

**Comment by sky-coding** [comment]
Opening a component into a modal works for me, here is most of the code you need:

```
class ModalData extends BSModalContext {
  constructor(public someData:string) {
    super();
  }
}

class CustomModal implements ModalComponent<ModalData> {
  someData:string;

  constructor(public dialog:DialogRef<ModalData>) {
    this.someData = dialog.context.someData;
  }


class MainComponent {
  constructor(public modal:Modal) {
  }
  
  open(){
    this.modal.open(CustomModal, new ModalData('foo'))
      .then((dialog:DialogRef<ModalData>) => {
        // on dialog creation

        dialog.result.then((returnData) => {
          // on close/save
          
        }, () => {
          // on dismiss/cancel
          
          
        });
        
      }, () => {
        // on failure to create dialog
      })
  }
}
```

I wasn't able to use bootstrap preset modals with a custom component, but it might be possible.

**Comment by shlomiassaf** [comment]
I'll close this stale issue, please re-open with a comment if it still an issue.
