### ISSUE TITLE
allow arbitrary class names for dialogClass method

### ISSUE THREAD

**Issue by lewisames** [shlomiassaf/angular2-modal#107]
It would be great if the dialogClass method could support arbitrary class names.  The behavior is already supported, but the typescript compiler throws errors since only "sm" and "lg" are defined as arguments.

**Comment by shlomiassaf** [comment]
You can post PR, it will help and that's an easy fix.

As a workaround you can just put `<any>'my-class'`

**Comment by lewisames** [comment]
Ok, I've modified the source.  Do I need permission to publish the PR?

**Comment by shlomiassaf** [comment]
no, just post it

**Comment by lewisames** [comment]
I'm getting some "Authentication Failed" errors from my github client.  I'll try again later.

**Comment by sime** [comment]
@shlomiassaf Thanks for sharing the `<any>'my-class'` workaround.

**Comment by shlomiassaf** [comment]
I'll close this stale issue, please re-open with a comment if it still an issue.
