### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by heidermatos** [shlomiassaf/angular2-modal#109]
> Steps to follow:

Installation angular2-modal: npm install angular2-modal --save

Registered the "MODAL_BROWSER_PROVIDERS" as follows:

`
import {} MODAL_BROWSER_PROVIDERS from 'angular2-modal / platform-browser';

Bootstrap (AppComponent, MODAL_BROWSER_PROVIDERS) .catch (err => console.error (err));
`

> I set the root element in my comoonent:

`
{import Component, ViewContainerRef} from '@ angular / core';
import {
    VEX_MODAL_PROVIDERS,
    Modal
} From 'angular2-modal / plugins / vex';

@Component ({
    ...
    viewProviders [... VEX_MODAL_PROVIDERS]
    ...
})

constructor (modal public: Modal, viewContainer: ViewContainerRef) {
        modal.defaultViewContainer = viewContainer;
    }

> My alert as my need:

openAlert () {
        return this.modal.prompt ()
           .className ( 'wireframe')
           .message ( 'Enter your name')
           .placeholder ( 'Your name here')
           .open ();
    }
`

> The wheels my application I get the error below:

> Rror: Error: XHR error (404 Not Found) loading http: // localhost: 5555 / node_modules / angular2-modal / platform-browser.js
> At XMLHttpRequest.wrapFn [the _onreadystatechange] (http: // localhost: 5555 / node_modules / zone.js / dist / zone.js 1465481854589: 745: 30)
> At ZoneDelegate.invokeTask (http: // localhost: 5555 / node_modules / zone.js / dist / zone.js 1465481854589: 339: 38)
> At Zone.runTask (http: // localhost: 5555 / node_modules / zone.js / dist / zone.js 1465481854589: 237: 48)
> At XMLHttpRequest.ZoneTask.invoke (http: // localhost: 5555 / node_modules / zone.js / dist / zone.js 1465481854589: 405: 34)
> Error loading http: // localhost: 5555 / node_modules / angular2-modal / platform-browser.js the "angular2-modal / platform-browser" from http: // localhost: 5555 / main.web.js "Report this error at https://github.com/NathanWalker/angular2-seed-advanced/issues"(anonymous function) @ localhost /: 124
> Http: // localhost: 5555 / node_modules / angular2-modal / plugins / vex.js Failed to load resource: the server responded with a status of 404 (Not Found)

This file is not in my angular2-mold package installed.
http: // localhost: 5555 / node_modules / angular2-modal / platform-browser.js

What can I be doing wrong, how should I proceed to correct this error?
Thank you.

**Comment by heidermatos** [comment]
RESOLVED!

> Instead of imported and

import {MODAL_BROWSER_PROVIDERS} from "angular2-modal/platform-browser";

> I imported this way

import {MODAL_BROWSER_PROVIDERS} from "angular2-modal/platform-browser/index";

and worked.

**Comment by shlomiassaf** [comment]
@heidermatos I assume you're using system js?

Did you set a main for the `angular2-modal/platform-browser` package? if you do that you can omit the index.

**Comment by lsiden** [comment]
@shlomiassaf Could you give me an example of setting "main"?  I did this in system-config.ts
    
    const packages: any = {
        'angular2-modal': {main: 'index.js', defaultExtension: 'js'}
    };

In main.ts:

    import {MODAL_BROWSER_PROVIDERS} from 'angular2-modal/platform-browser';

Chrome developer console says:

    zone.js:101 GET http://localhost:4200/angular2-modal/platform-browser.js 404 (Not Found)

Isn't import supposed to resolve 'angular2-modal/platform-browser' as 'angular2-modal/platform-browser/index.ts'?

**Comment by lsiden** [comment]
I followed @heidermatos and added '.../index', but got:

    zone.js:101 GET http://localhost:4200/angular2-modal/platform-browser/index.js 404 (Not Found)

To keep it simple, I left system-config.js alone.

**Comment by lsiden** [comment]
@shlomiassaf Would you like me to submit a pull-request with this info updated to the README?

**Comment by shlomiassaf** [comment]
@lsiden Yes, I will appreciate it a lot!

**Comment by shlomiassaf** [comment]
I'll close this stale issue, please re-open with a comment if it still an issue.

See #152
