### ISSUE TITLE
Attach event to buttons

### ISSUE THREAD

**Issue by ImranAhmed** [shlomiassaf/angular2-modal#110]
Hi,

Are there any examples of how you actually attach an event to the buttons? Maybe I've missed something but it's not clear.

This creates a modal with ok/cancel. However how do you actually attach to the ok/cancel button?
```
modal.confirm()
    .size('sm')
    .isBlocking(true)
    .showClose(true)
    .keyboard(27)
    .title('Hello World')
    .body('A Customized Modal')
    .open();
```

**Comment by shlomiassaf** [comment]
Every modal window is built of several component.

The main on is the actual dialog component that shows the dialog content, inside there are (among other things) the OK/CANCE buttons.

The buttons bind to the component itself.

This component can be replaces, that's the actual power.

In your example, you use the built in component that angular2-modal comes with. Inside that component there are bindings for these events, you don't really need them.

The returned value, from the expression in your sample, returns a promise and you handle it to get the result (resolve/reject of that promise)

Now the confusing part here might be that the response is a promise inside a promise.

The value returned from the call to `open()` is a promise for the modal creation, i.e creating the modal as a component. This is just how angular 2 works - creating a component is an async operation.

From that promise you get an object with a `result` property which is a promise for the result.

The API could easily hide the first promise from the end user but I want to keep within angular's structure.

It's an easy operation, to merge these 2 into one, but it will be harder to understand where an error comes from.

See this sample for the whole process:

```ts
const dialog = modal.confirm()
    .size('sm')
    .isBlocking(true)
    .showClose(true)
    .keyboard(27)
    .title('Hello World')
    .body('A Customized Modal')
    .open();

 dialog.then((resultPromise) => {
            return resultPromise.result.then((result) => {
                this.result = result;
            }, () => this.result = 'Rejected!');
        });
```

**Comment by ImranAhmed** [comment]
Thanks, works a treat!
