### ISSUE TITLE
Bootstrap animation bug v1.0.6

### ISSUE THREAD

**Issue by CaselIT** [shlomiassaf/angular2-modal#116]
I'm submitting a bug report.
These seems to be an problem with the animation in the bootstrap plugin:
Example: cannot open a modal on http://shlomiassaf.github.io/angular2-modal#/bootstrap-demo
I get the error `EXCEPTION: Error in ./BSModalContainer class BSModalContainer - inline template:3:10` `ORIGINAL EXCEPTION: TypeError: Failed to execute 'animate' on 'Element': 'null' is not a valid value for easing`

**Comment by shlomiassaf** [comment]
I'm not able to reproduce, please supply a plunker.

**Comment by CaselIT** [comment]
Strange,
I get the error also on the demo site. And I've check and it should not be a cache problem on my end.
In any case, [here's a plunker](http://plnkr.co/edit/r2ATUw?p=preview). Clicking on open Modal will cause the error.
Sorry for not adding it from the start. I've also done some tests and the bug happens on Chrome 52 and Firefox 48b1, but not on Edge or IE ( :open_mouth: )

**Comment by mahpah** [comment]
Confirmed this bug occurred in Chrome v 53.0.2767.4 dev (64-bit). In FF it work. I've tested with the demo page.
I've try to remove 'void => in' keyframe animation and it work. I guess it related to angular animation.
When I close modal, '* => out' did not work to.

**Comment by shlomiassaf** [comment]
This is probably a bug in the animation module in angular 2, we need to pin point it before we can open an issue there.

**Comment by CaselIT** [comment]
It seems that the problem solved itself. I no longer have it...

@shlomiassaf Do you plan to add an option to disable the animations?

**Comment by CaselIT** [comment]
Actually still on the demo site, but no longer on the plunker.
Maybe angular rc3 solved it?

**Comment by shlomiassaf** [comment]
@CaselIT maybe, i'll upgrade and see.

About animations, I don't know, maybe.
It should be easy, just play with the states..

I have some issues with the animations, there's a workaround to make the 'close' animations work since I remove the container and this doesn't trigger child animations.

If this is by design from angular I need to change my design to notify children to close and report back when done... this will be a burden on plugins... I want to wait a bit to see the next versions of animation

**Comment by CaselIT** [comment]
I think I've found the bug, and the reason why on some browser it is working and in some it is not.
The problem is caused by the comma [here](https://github.com/shlomiassaf/angular2-modal/blob/master/src/components/angular2-modal/plugins/bootstrap/modal-backdrop.ts#L45) in `150ms, linear` and [here](https://github.com/shlomiassaf/angular2-modal/blob/master/src/components/angular2-modal/plugins/bootstrap/modal-container.ts#L40) in `100ms, linear` which causes angular to not recognise the easing.

The reason some browser are not affected is that they use the mock `NoOpAnimationPlayer` animation player defined [here](https://github.com/angular/angular/blob/master/modules/%40angular/core/src/animation/animation_player.ts#L32) 

The pull request #131 fixes the issue

**Comment by shlomiassaf** [comment]
@CaselIT 
I don't think the `,` is the issue (if it is, it's a bug in angular animation's parser allowing it or not handling it)

The issue in the demo site is that I didn't include the web animation pollyfil which result in a non working animation on browsers that does not support web animation.

For example, [this plunker](http://plnkr.co/edit/dcdkL14QQQldbsV60Yl9?p=preview)
I have 2 identical animations one with `150ms, linear` and one with `150ms linear`.
Both work on Chrome in my mac.
Both doesn't work on FF in my mac.

Now adding
```
<script src="https://web-animations.github.io/web-animations-demos/components/web-animations-js/web-animations-next.min.js"></script>
```

To the `index.html` will add the polyfill.
Checking on FF again, **both** work.... so a comma is valid.

**Comment by shlomiassaf** [comment]
I'll fix it but it's a bug in the demo site, not in the module since a user must opt in the polyfil.

**Comment by CaselIT** [comment]
I checked the plunker. On win10, the one with the , do not work on ff or chrome, the other does.
Adding the polyfill does not change anything for me..

**Comment by CaselIT** [comment]
This may be an angular problem.
The [regexp used by angular to parse the animation](https://github.com/angular/angular/blob/master/modules/%40angular/compiler/src/animation/animation_parser.ts#L468) does not support the comma. Without comma it correctly [parses](https://regex101.com/r/cJ0mY5/1), but not with a [comma](https://regex101.com/r/sV5qO2/2)

**Comment by LeraKruchek** [comment]
I was able to reproduce the bug - win 10, chrome 52.0.2743.82 m (64-bit)
[CaselIT solution](https://github.com/CaselIT/angular2-modal/commit/801cfb8ad53da1b5f66598f849855d0e64cfd3f4) worked for me.

Also reproducible on demo page.

**Comment by CaselIT** [comment]
Since I needed to install the fix via npm I've created an installable branch with it here https://github.com/CaselIT/angular2-modal/tree/forked-npm. It also contains the fix for https://github.com/shlomiassaf/angular2-modal/issues/132

It can be installed by using `"angular2-modal": "github:caselit/angular2-modal#forked-npm"` in the package.json

**Comment by noorahmed94** [comment]
When are the changes going to merge in package?

**Comment by CaselIT** [comment]
Only @shlomiassaf  can answer..
