### ISSUE TITLE
Bootstrap prompt does not have an input field

### ISSUE THREAD

**Issue by CaselIT** [shlomiassaf/angular2-modal#119]
* I'm submitting a feature request

Hi @shlomiassaf 
Is it me or Bootstrap prompt does not have an input field, contrary to the vex one?

I may be able to help implement it, do you have any suggestions?

**Comment by shlomiassaf** [comment]
Give it a go, look at the custom modal example for bootstrap, it look like a prompt.

**Comment by CaselIT** [comment]
:+1: 

I've notices there is quite a bit of difference between the implementation of the vex plugin and the bootstrap one. Also maybe some code could be shared between the two. Do you plan to refactor it to harmonize the two?

**Comment by shlomiassaf** [comment]
Yes, I'm working on it.
The modal library should provide a simpler approach for plugins.

I did the background things, now most of the work is simplifying the plugins, I do design as I go, so I don't have something to share but i'll post something soon

**Comment by CaselIT** [comment]
:+1: 
It was not meant to urge you.
Great work so far :rose:
