### ISSUE TITLE
popover style modal support

### ISSUE THREAD

**Issue by lanocturne** [shlomiassaf/angular2-modal#12]
Hi, just wander is it possible to create a modal like this style http://v4-alpha.getbootstrap.com/components/popovers/ ?

The thing is I need to put template in a popover rather than text.

**Comment by sunnyque** [comment]
I think you need something like this: http://stackoverflow.com/questions/16226474/how-can-i-close-a-bootstrap-popover-with-a-button-inside-the-popover

you don't need angular2-modal for that (I suppose it is not suitable for your task)

**Comment by shlomiassaf** [comment]
@sunnyque is right, popovers are a different creature.
The depend on an element they are attached to (aligned relative to that element)
They dont have a backdrop...

Something different...
