### ISSUE TITLE
hi, how can i use nested modal?

### ISSUE THREAD

**Issue by karthikkavin** [shlomiassaf/angular2-modal#122]
IMPORTANT: Please provide a sample using http://plnkr.co/edit/iiQett?p=preview 

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/iiQett?p=preview).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by karthikkavin** [comment]
How to use nested modal window?. This feature is available now?

**Comment by shlomiassaf** [comment]
Go to http://shlomiassaf.github.io/angular2-modal#/bootstrap-demo
Click on the **Cascading example** button

Now, go to https://github.com/shlomiassaf/angular2-modal/blob/master/src/demo/app/bootstrap-demo/presets.ts#L61 and see how it's implemented.

Learning form samples is the way to go, I have no help so no docs.

**Comment by shlomiassaf** [comment]
I'll close this stale issue, please re-open with a comment if it still an issue.

**Comment by karthikkavin** [comment]
hi sir, i have an issue for when we open a dialog, this dialog has a button and that button to click to show another dialog. 
how is do?

**Comment by karthikkavin** [comment]
can please advise common modal component to use and bind template and data and retrieve?

**Comment by shlomiassaf** [comment]
I don't understand the question, please try to explain again

**Comment by shlomiassaf** [comment]
Here is a sample how to open a modal from a modal
http://plnkr.co/edit/c1vfzn?p=preview

**Comment by karthikkavin** [comment]
When we use one dialog  and it have a component. In our development we used this dialog on commonly used our purpose. we just replace the header, body sections to avoid more code write.
can you advise please.
