### ISSUE TITLE
angular2-modal breaks with  RC4 release

### ISSUE THREAD

**Issue by chandermani** [shlomiassaf/angular2-modal#125]
* **I'm submitting a ...**
[ Y] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Post Angular RC4 update, Angular2-modal version `1.0.7` throws compilation  error when compiled with TypeScript compiler. 

```
.../node_modules/angular2-modal/platform-browser/outside-event-plugin.d.ts(1,10): 

error TS2305: Module '"...node_modules/@angular/platform-browser/index"' has no exported member 'DomEventsPlugin'.
```
This may be due to this [RC4 change](https://github.com/angular/angular/blob/master/CHANGELOG.md)

> Previously deprecated BROWSER_PROVIDERS was completely removed from platform-browser.

**Comment by mahpah** [comment]
I'm facing the same issue today. `DomEventsPlugin` is still there, wasn't removed, but no longer export. You can import it from `@angular/platform-browser/src/dom/events/dom_events.ts`, but import from src is  very bad idea.

**Comment by rbuskov** [comment]
I guess RC3 works OK then? Can anyone confirm?

**Comment by shlomiassaf** [comment]
DomEventsPlugin is now a private class, I will upgrade to rc4 and remove the dependency

**Comment by ZachHardin** [comment]
After upgrading I was still getting the same error until I ran npm cache clean, in case anyone else runs in to this.
