### ISSUE TITLE
i have an issue loading the angular2-modal with rc1

### ISSUE THREAD

**Issue by gatof81** [shlomiassaf/angular2-modal#127]
sorry no sample
[responsive-application.js:84712 Uncaught TypeError: core_1.style is not a function ] bug report
all browsers
VEX modal works perfectly but as soon as i load bootstrap page throw that error!
im using angular2->2.0.0-rc.1

**Comment by shlomiassaf** [comment]
I can't really support RC1, if you want to use RC1 use the last version of angular2-modal that supported RC1 in the package.json file.

**Comment by gatof81** [comment]
You are totally right, I should have thought of this earlier, thank you very much! 
Do you by any chance know which might be the last version to support rc1? 
If not never mind and I very appreciated for your response!
