### ISSUE TITLE
error

### ISSUE THREAD

**Issue by DeepshikhaKalra** [shlomiassaf/angular2-modal#130]
Hi, I just included angular2-modal, and  I am seeing this error
<details>
<summary>Error: BSModalContainer<@http://localhost/node_modules/angular2-modal/plugins/bootstrap/modal-container.js:79:29</summary>
	@http://localhost/node_modules/angular2-modal/plugins/bootstrap/modal-container.js:18:25
	@http://localhost/node_modules/angular2-modal/plugins/bootstrap/modal-container.js:1:31
	@http://localhost/node_modules/angular2-modal/plugins/bootstrap/modal-container.js:1:2
	@http://localhost/node_modules/angular2-modal/plugins/bootstrap/modal-backdrop.js:13:25
	@http://localhost/node_modules/angular2-modal/plugins/bootstrap/modal-backdrop.js:1:31
	@http://localhost/node_modules/angular2-modal/plugins/bootstrap/modal-backdrop.js:1:2
	@http://localhost/node_modules/angular2-modal/plugins/bootstrap/index.js:4:24
	@http://localhost/node_modules/angular2-modal/plugins/bootstrap/index.js:1:31
	@http://localhost/node_modules/angular2-modal/plugins/bootstrap/index.js:1:2
	@http://localhost/app/login/login.js:24:15
	@http://localhost/app/login/login.js:1:31
	@http://localhost/app/login/login.js:1:2
	@http://localhost/app/mainAppComponent/main.AppComponent.js:20:15
	@http://localhost/app/mainAppComponent/main.AppComponent.js:1:31
	@http://localhost/app/mainAppComponent/main.AppComponent.js:1:2
	@http://localhost/app/main.js:10:27
	@http://localhost/app/main.js:1:31
	@http://localhost/app/main.js:1:2
	Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost/node_modules/zone.js/dist/zone.js:323:20
	Zone</Zone</Zone.prototype.run@http://localhost/node_modules/zone.js/dist/zone.js:216:25
	scheduleResolveOrReject/<@http://localhost/node_modules/zone.js/dist/zone.js:571:53
	Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost/node_modules/zone.js/dist/zone.js:356:24
	Zone</Zone</Zone.prototype.runTask@http://localhost/node_modules/zone.js/dist/zone.js:256:29
	drainMicroTaskQueue@http://localhost/node_modules/zone.js/dist/zone.js:474:26
	ZoneTask/this.invoke@http://localhost/node_modules/zone.js/dist/zone.js:426:22
	
	Evaluating http://localhost/node_modules/angular2-modal/plugins/bootstrap/modal-container.js
	Evaluating http://localhost/node_modules/angular2-modal/plugins/bootstrap/modal-backdrop.js
	Evaluating http://localhost/node_modules/angular2-modal/plugins/bootstrap/index.js
	Evaluating http://localhost/app/login/login.js
	Evaluating http://localhost/app/mainAppComponent/main.AppComponent.js
	Evaluating http://localhost/app/main.js
	Error loading http://localhost/app/main.js zone.js:323:20
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke() zone.js:323
Zone</Zone</Zone.prototype.run() zone.js:216
scheduleResolveOrReject/<() zone.js:571
Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask() zone.js:356
Zone</Zone</Zone.prototype.runTask() zone.js:256
drainMicroTaskQueue() zone.js:474
ZoneTask/this.invoke() zone.js:426
</details>

**Comment by shlomiassaf** [comment]
Pluker please, i'm still can't read minds :)

**Comment by shlomiassaf** [comment]
I'll close this stale issue, please re-open with a comment if it still an issue.
