### ISSUE TITLE
Default event is prevented when more than a dialog is open

### ISSUE THREAD

**Issue by CaselIT** [shlomiassaf/angular2-modal#132]
* **I'm submitting a bug report**

* **What is the current behavior?**

When two or more modal are displayed the default event is prevented. 
In the [example](http://plnkr.co/edit/aKqS9Q?p=preview) a checkbox on the second modal cannot be clicked.

The error is caused by the return in the function `onClickOutside` in [bootstrap](https://github.com/shlomiassaf/angular2-modal/blob/master/src/components/angular2-modal/plugins/bootstrap/modal-container.ts#L112) and [vex](https://github.com/shlomiassaf/angular2-modal/blob/master/src/components/angular2-modal/plugins/vex/modal-content.ts#L64). These function are called by [angular](https://github.com/angular/angular/blob/master/modules/%40angular/platform-browser/src/dom/dom_renderer.ts#L267) and since they return false if the modal is not the topmost the default is event is prevented.

Removing the return from `onClickOutside` fixes the problem.
I can make a PR if the solution does not break anything else.

**Comment by CaselIT** [comment]
I think that another possible solution is to disable the `onClickOutside` logic when the modal is not the topmost.

**Comment by CaselIT** [comment]
I've used the solution mentioned in the commit and it works for me

**Comment by shlomiassaf** [comment]
@CaselIT, can you make a PR?
