### ISSUE TITLE
(Question) configuring dismiss options for custom modal

### ISSUE THREAD

**Issue by greg73** [shlomiassaf/angular2-modal#133]
Hi,
I have implemented a custom bootstrap modal but I can't see how to configure the options to allow/disallow pressing escape and/or clicking outside the modal to dismiss it. Hopefully this is straightforward but I haven't been able to find it.

Thanks

**Comment by arnjmllr** [comment]
I think you are looking for .isBlocking(false)
example: 
this.modal.confirm().message("Are you sure?").isBlocking(false).open();

pressing ESC did not dismiss ,but clicking outside the modal did.

**Comment by greg73** [comment]
Thanks but this is a custom modal using this.modal.open() which doesn't have the isBlocking option

**Comment by shlomiassaf** [comment]
In version 2 you create a custom modal using an `OverlayConfig` as a parameter.
See it in the [demo](https://github.com/shlomiassaf/angular2-modal/blob/master/src/demo/app/bootstrap-demo/bootstrap-demo-page/bootstrap-demo-page.ts#L44-L54)

You can then easily add the isBlocking:
```ts
          const builder = new BSModalContextBuilder<CustomModalContext>(
            { num1: 2, num2: 3 } as any,
            undefined,
            CustomModalContext
          );

          let overlayConfig: OverlayConfig = {
            context: builder.isBlocking(true).toJSON()
          };

          return this.modal.open(CustomModal, overlayConfig);
```

**Comment by greg73** [comment]
Thank you.  A very useful library  :+1:
