### ISSUE TITLE
No provider for XXXXX

### ISSUE THREAD

**Issue by ajbeaven** [shlomiassaf/angular2-modal#137]
I think the (previously resolved) error mentioned in the docs may be back in Angular 2.0.0-rc.4. If my custom modal component uses a directive that loads a service using DI, I get the following error:

`No provider for MyService`

I'm new to Angular so please forgive me if I've done something else silly to cause this error. You can take a look at [this plunker](http://plnkr.co/edit/29R21f?p=preview) to see the problem behaviour.

**Comment by shlomiassaf** [comment]
You forgot to set the provider in the `providers` list.

```ts
import {Component} from '@angular/core';
import {MyService} from './myservice';

/**
 * A Sample of how simple it is to create a new window, with its own injects.
 */
@Component({
    selector: 'modalcomponent',
    providers: [ MyService ],
    template: `
     ** Modal component successfully loaded **
    `
})
export class ModalComponentComponent implements ModalComponent<AdditionCalculateWindowData> {
    constructor(public service: MyService) {
    }
}
```

>Note that on the next angular version (RC5) this will change a bit, but for RC4 it will work.

**Comment by ajbeaven** [comment]
I had done this on purpose as I was expecting the service in AppComponent to be passed through as it should be available to all child components. A single instance of this service needs to be shared across a number of components. Sorry, I should have mentioned this is my initial report.  

From my limited understanding, adding it to that providers array will create a separate instance of the dependency so that solution won't work for me unfortunately.

**Comment by shlomiassaf** [comment]
This is angular DI question and understanding.

In any case, at least 1 instance is created, right?

So, if you create it at the Root component level it will bubble down, unless a new provider is defined in child componetns, they will all get the same instance defined in that root component.

You can also define the provider in the bootstrap providers array (or in the next RC5 in the `@NgModule`.

You can choose the best strategy.

Anyway, it's an angular issue.

**Comment by ajbeaven** [comment]
Sorry, I'm confused - are you saying that this is a bug in angular? My original plunker already defined the service in its providers array - the bubbling down is what isn't working and instead an error is thrown. 

I figured this was perhaps an angular2-modal issue as this bubbling down works correctly in all other child components.

**Comment by cuiliang** [comment]
Also see this problem. seems like component in angula2-modal  can not inherit providers from root component.

**Comment by cuiliang** [comment]
Move providers from root component to `bootstrap` method solve the problem.
