### ISSUE TITLE
Security warning

### ISSUE THREAD

**Issue by mclouvem** [shlomiassaf/angular2-modal#139]
IMPORTANT: Please provide a sample using http://plnkr.co/edit/iiQett?p=preview 

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Using a confirm modal within an Angular2 project running in Google Chrome, it shows some security alerts regarding XSS.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/iiQett?p=preview).

* **What is the expected behavior?**
No security warnings

* **What is the motivation / use case for changing the behavior?**

Security improvements / reliability 

* **Please tell us about your environment:**

- Angular version: 2.0.0-RC-4
- Browser: [all | Chrome 51 | Firefox 49 | IE 11 | Edge ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

WARNING: sanitizing HTML stripped some content (see http://g.co/ng/security#xss).

**Comment by shlomiassaf** [comment]
If only I knew what was stripped...

**Comment by sergeome** [comment]
I've got the same error when trying to embed input tag into body. For example:
```
body('
<input type="text">
') 
```

![xss](https://cloud.githubusercontent.com/assets/10011693/18693094/bfcd9728-7f64-11e6-94ec-69f92b170793.png)

**Comment by mclouvem** [comment]
@sergeome In my case, it's due special characters (in Portuguese). And don't know what should I do to avoid these warnings

**Comment by shlomiassaf** [comment]
The striped HTML seems harmless, I don't know the exact cause  in the templates but it can be investigated later on.

Will close now and we will deal with this later.

**Comment by javi830810** [comment]
Allow me to disagree. This warning makes this popup unusable for input forms, how can you call this harmless?
