### ISSUE TITLE
Use the package without dependencies (e.g. webpack, require)

### ISSUE THREAD

**Issue by RamiMustaklem** [shlomiassaf/angular2-modal#14]
Is there a way to use the package without webpack and require and all other libraries dependencies?
When installing the package through npm, it imports everything on your repository, including the node_modules folder you've used.
You haven't provided an example for using the package through the angular2_modal only.

**Comment by shlomiassaf** [comment]
Moved angular2 & bootstrap as to devDependencies.

Thanks!

**Comment by RamiMustaklem** [comment]
I meant using the library, just importing the angular2_modal file to index and that's it. No webpack no require. Is it possible?
