### ISSUE TITLE
Unable to get clicked button

### ISSUE THREAD

**Issue by vargalas** [shlomiassaf/angular2-modal#146]
Possibly it's just something I haven't found out, yet, but I'm trying this for a half day now and I cannot solve it.
I'd like to create a confirmation dialog.
This is how I tried:
```
    this.modal.confirm()
      .size('sm')
      .isBlocking(true)
      .showClose(false)
      .keyboard(27)
      .body('Are you sure?')
      .okBtn('YES')
      .cancelBtn('NO')
      .open().then((dialog: DialogRef<TwoButtonPreset>) => {
        dialog.onDestroy.subscribe((value) => {
         //something
      })
      });
```
For me it seems that the open returns a promise with the dialog object as the value. It is fired when the dialog is created.
I can observe the dialog on destroy, but the value is always null. 
I found that the dialog has a close method, but it closes the dialog itself. 

Sorry if it's really dummy: how can I get the clicked button and run my code when the OK button was pressed?

**Comment by CaselIT** [comment]
You can use the `dialog.result` promise.

```ts
...
.then((dialog: DialogRef<TwoButtonPreset>) => {
        dialog.result.then(result=>{
            // Ok button called
        }).catch(()=>{
            // Cancel button called
        })
)
```

I hope it helps. Have a look the sample website also

**Comment by vargalas** [comment]
Thank you very much!

**Comment by secabhi** [comment]
@CaselIT how i can keep alive modal even after ok clicked . After ok button click modal is closing . I dont want to do that .

**Comment by CaselIT** [comment]
I've never tried. You could try to add a new OK button that does what you want end hide the default one by setting its css class so it is not displayed. 
```ts
modal.confirm()
  .okBtnClass('hide')
  .addButton(...)
```
```css
.hide {
  display:none;
}
```
I've not tested it so I'm not sure if it works.

As an alternative you could create a new component so you have complete control of everything.

**Comment by secabhi** [comment]
@CaselIT Thanx . But I just wanted to prevent modal from being close on OK button

**Comment by CaselIT** [comment]
What I suggested should do that.

On 3 Feb 2017 16:51, "Abhishek Sinha" <notifications@github.com> wrote:

@CaselIT <https://github.com/CaselIT> Thanx . But I just wanted to prevent
modal from being close on OK button

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/shlomiassaf/angular2-modal/issues/146#issuecomment-277283409>,
or mute the thread

**Comment by rrohitesh** [comment]
How Can we capture then return of this on the button press

```
 onWarning(title: String, message: String) {
  return this.modal.alert()
            .size('sm')
            .showClose(false)
            .isBlocking(true)
            .okBtn(null)
            .okBtnClass('hide-ok')
            .addButton('btn btn-default', 'Accept', function (dialogFooter) {
                console.log('ok calback');
                dialogFooter.dialog.dismiss();
                response = true;
                return false;
            })
            .addButton('btn btn-default', 'Discard', function (dialogFooter) {
                console.log('cancle calback');
                dialogFooter.dialog.dismiss();
                response = false;
                return true;
            })
            .body(`
                <div class="modal-body">
                <div class="header-image">     
            <i class="fa fa-exclamation-triangle fa-lg" aria-hidden="true" ></i>
                </div>
                    <h1>` + title + `</h1>
                    <div class="modal-message">` + message + `</div></div>`)
            .open().then(result => {
                console.log('result', result);

            });
}
```
I want this function to return true or false based on the ACCEPT or DISCARD callback button pressed.
