### ISSUE TITLE
(Question) How we can provide some data between base and modal components?

### ISSUE THREAD

**Issue by basters** [shlomiassaf/angular2-modal#148]
Hi everyone. I want to solve a simple task:
1) Open modal window with prepared data (form data)
2) Visualize form data in the modal form
3) Get modified data back from the window in my base component.

Well, the reason question: How I can do it?

Yes, sure, I can create the service and use him as provider between modal and base components, but this way not always possible because I should to declare my service as Provider in parent component, but I can't do it in my task.

I just want to pass data and get it in promise, like in ngDialog for angular 1.x

**Comment by LifeguardConcepts** [comment]
Basters, check out the custom modal window example.

Its the last modal to be called on the demo src: 
https://github.com/shlomiassaf/angular2-modal/blob/master/src/demo/app/bootstrap-demo/bootstrap-demo-page/bootstrap-demo-page.ts

Custom Window src:
https://github.com/shlomiassaf/angular2-modal/blob/master/src/demo/app/bootstrap-demo/bootstrap-demo-page/custom-modal-sample.ts

On the call back promise you can capture the result call back to get any data you have passed back in the result.

**Comment by shlomiassaf** [comment]
I'll close this stale issue, please re-open with a comment if it still an issue.
