### ISSUE TITLE
Package the ts files in dist.

### ISSUE THREAD

**Issue by bertvh** [shlomiassaf/angular2-modal#15]
I installed via npm. The dist dir contains js, d.ts and .map files. However, not the original ts sources. Chrome doesn't allow you to set a breakpoint on the js directly if there is a mapping file present. It switches to the (non-existing) ts file.

Could you add them?

**Comment by shlomiassaf** [comment]
Added src directory to npm package.
Let me know if it works.

**Comment by shlomiassaf** [comment]
See 0.0.3, please update me so I can close this.

**Comment by bertvh** [comment]
It works. Thanks!
