### ISSUE TITLE
404 error on npmcd.com

### ISSUE THREAD

**Issue by thardes2** [shlomiassaf/angular2-modal#152]
IMPORTANT: Please provide a sample using http://plnkr.co/edit/iiQett?p=preview 
 ---> Just use your examples

* **I'm submitting a ...**
[*] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
I am using angular2-model since a few weeks and today I get an 404-error for the URI https://npmcdn.com/angular2-modal@1.1.0/platform-browser/index.js 

* **What is the motivation / use case for changing the behavior?**
Even your examples are not working any more - maybe this is because of the same issue

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.5
- Browser: electron (Chrome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by shlomiassaf** [comment]
The `platform-browser` does not exist in 1.1.0

**Comment by thardes2** [comment]
None of your examples is working - do you have the plan to fix this?

**Comment by shlomiassaf** [comment]
Please try version 1.1.1

See working sample in [this plunker](http://embed.plnkr.co/hwbmF9/)

**Comment by thardes2** [comment]
Thank you
