### ISSUE TITLE
Custom Modal dialog is not working with Angular2-modal 1.1.1 and Angular2 RC5

### ISSUE THREAD

**Issue by ssashok10** [shlomiassaf/angular2-modal#155]
I'm submitting a bug report with angular2-modal V 1.1.1

As per the documentation, I have added the below line on my project,

`import { MODAL_BROWSER_PROVIDERS } from 'angular2-modal/platform-browser/index';`

However, there is no sub folder "platform-browser" exists under the folder "angular2-modal".  I am using Angular2-modal 1.1.1 and Angular 2 RC 5.

This should be bug or the documents are not updated with the latest changes.  Please let me know. Thanks in advance.

**Comment by ssashok10** [comment]
I made it working for the basic modal based on the below sample,

`http://embed.plnkr.co/hwbmF9/`

However, my existing custom modal is not working and i get the below error,

**browser_adapter.ts:82EXCEPTION: No component factory found for "xxxx".**

Here is my code to call custom dialog,

`const dialog = this.modal.open(CustomComponent, new CustomContextData("Closed"));`

**Comment by shlomiassaf** [comment]
Here's a [plunker sample](http://plnkr.co/edit/hwbmF9?p=preview)

**Comment by ssashok10** [comment]
Adding "entryComponents" on the app.module.ts solved the issue. Thanks for the help.
