### ISSUE TITLE
Error in type definitions for the bootstrap plugin.

### ISSUE THREAD

**Issue by xkill-9** [shlomiassaf/angular2-modal#156]
There seems to be an outdated import in these files:

```
ERROR in .../node_modules/angular2-modal/plugins/bootstrap/message-modal.d.ts
(1,43): error TS2307: Cannot find module '../../../../components/angular2-modal'.

ERROR in .../node_modules/angular2-modal/plugins/bootstrap/modal-container.d.ts
(2,47): error TS2307: Cannot find module '../../../../components/angular2-modal'.

ERROR in .../node_modules/angular2-modal/plugins/bootstrap/modal-backdrop.d.ts
(2,27): error TS2307: Cannot find module '../../../../components/angular2-modal'.
```

Here's the broken import in each file:

```
// message-modal.d.ts
import { DialogRef, ModalComponent } from '../../../../components/angular2-modal';

// modal-container.d.ts
import { DialogRef, ModalCompileConfig } from '../../../../components/angular2-modal';

// modal-backdrop.d.ts
import { DialogRef } from '../../../../components/angular2-modal';
```

EDIT: 
I'm using the latest version (1.1.1), btw.

**Comment by noorahmed94** [comment]
@shlomiassaf is it fixed?

**Comment by shlomiassaf** [comment]
No, I use a script to replace all relative imports in plugins to absolute.
e.g: `import { DialogRef, ModalComponent } from '../../../../components/angular2-modal';`
becomes: `import { DialogRef, ModalComponent } from 'angular2-modal`

But it's done on the JS files, so the d.ts files are left out.
I'll fix that.

**Comment by wittegijt** [comment]
These two files still have the "Cannot find module '../../../../components/angular2-modal'" error in 1.1.3. 

plugins/bootstrap/index.d.ts,
plugins/bootstrap/presets/two-button-preset.d.ts

**Comment by shlomiassaf** [comment]
Yep, the regex wasn't greedy.
fixed
