### ISSUE TITLE
Bootstrap plugin fails in minified RC5 build

### ISSUE THREAD

**Issue by LeraKruchek** [shlomiassaf/angular2-modal#157]
* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
Minified bundle breaks with errors

Unhandled Promise rejection: Template parse errors:
Can't bind to 'footerClass' since it isn't a known property of 'modal-footer'.
1. If 'modal-footer' is an Angular component and it has 'footerClass' input, then verify that it is part of this module.
2. If 'modal-footer' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.

* **Steps to reproduce** 
run a minified version e.g. ng serve --prod

* **What is the expected behavior?**
The minified bundle should work as in RC4

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.5
-  Angular2-modal version 1.1.1
- Browser: [Chrome]

* **Other information** 
Suggestion how to fix:
I have changed the order of module declarations in bootstrap.module.ts and it worked for me

not working:
`@NgModule({
  imports: [ CommonModule ],
  declarations: [
    BSModalBackdrop,
    BSMessageModal,
    BSModalContainer,
    BSModalFooter
  ],
  providers: getProviders(),
  entryComponents: [
    BSModalBackdrop,
    BSMessageModal
  ]
})`

working:
`@NgModule({
  imports: [ CommonModule ],
  declarations: [
    BSModalFooter,
    BSMessageModal,
    BSModalBackdrop,
    BSModalContainer
  ],
  providers: getProviders(),
  entryComponents: [
    BSModalBackdrop,
    BSMessageModal
  ]
})`

@shlomiassaf 
please take a look at  https://github.com/angular/angular/issues/10618 - it's exactly the same

**Comment by shlomiassaf** [comment]
Thank you, actually I ran into this today when I tried to minify the demo site.

I will get to it, thanks.
