### ISSUE TITLE
templateUrl and styleUrls don't work

### ISSUE THREAD

**Issue by Nick0n** [shlomiassaf/angular2-modal#162]
Unfortunately `templateUrl` and `styleUrls` don't work as they should. HTML and styles are no being loaded.

**Comment by shlomiassaf** [comment]
A plukner sample would be helpful.

**Comment by Nick0n** [comment]
Yes, plunker works fine, but the styles and template are included inline. So I still think, there is an issue with it. Or maybe I missed something and there is a plunker with

**Comment by shlomiassaf** [comment]
It is a common practice to provide a plunker sample so one can reproduce the issue.

Put up a plunker showing the error so I can start working it out.

**Comment by Nick0n** [comment]
http://embed.plnkr.co/tiGpgA3gTkKJZxM7ZkYz/

In plunker this is not even loading...

**Comment by shlomiassaf** [comment]
It works for me...

just use absolute paths (or relative via moduleId)

```
styleUrls: ['app/custom-modal-sample.css']
templateUrl: 'app/custom-modal-sample.html'
```

**Comment by Nick0n** [comment]
Such a stupid mistake... Thanks

**Comment by shlomiassaf** [comment]
@Nick0n not at all... it's not you it's systemJS
