### ISSUE TITLE
Modal positioning on large templates

### ISSUE THREAD

**Issue by gustav77** [shlomiassaf/angular2-modal#163]
IMPORTANT: Please provide a sample using:  

  * V1: http://plnkr.co/edit/hwbmF9?p=preview 
  * V2: http://plnkr.co/edit/7c0pGE?p=preview

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

bug

* **What is the current behavior?**

If you add some more lines <p>...</p> to your demo plunkr and than click one of the modal buttons the modal opens but the upper part is hidden. If the page is long enough the modal isn't visible anymore.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use one of the templates above as a starting point).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by shlomiassaf** [comment]
Plunker please...

**Comment by gustav77** [comment]
Here is a plunkr:
http://plnkr.co/edit/TyOHY07jkLBX9jSnvR7h?p=preview

When I click the Alert Button, the problem shows. Tested on MacBook Air with Chrome and Firefox.

**Comment by shlomiassaf** [comment]
Yes, you're right the backdrop should be positioned `fixed` not `absolute`

**Comment by shlomiassaf** [comment]
See [this plunker](https://plnkr.co/edit/10hxji?p=preview)

BTW, you're plunker used beta.2, please use beta.8
