### ISSUE TITLE
"isBlocking" property missing [ 2.0.0-beta.9 ]

### ISSUE THREAD

**Issue by ssashok10** [shlomiassaf/angular2-modal#165]
* **I'm submitting a ...**
[ ] bug report

The older versions of the Modal dialogs having the proeprty "isBlocking" to implement the blocking dialog box. However, I am not able to see this property on the newer version 2.0.0-beta.9. I want to block the execution until the user clicks the OK button. Please let me know why i am not seeing the  "isBlocking" property on the newer versions.

```
 this.modal.prompt()
                    .showClose(true)
                    .message('Success')
                    .open()
```

**Comment by shlomiassaf** [comment]
In my test project I don't see any issues.

![image](https://cloud.githubusercontent.com/assets/5377501/17909405/0d49aafc-698d-11e6-9497-cd41dbc295a6.png)

**Comment by ssashok10** [comment]
Here is my code,

 this.modal.prompt()
                    .isBlocking(true)
                    .showClose(true)
                    .message('Your permission is updated')
                    .open()
                    .then((resultPromise) => { 
                        this.router.navigate(['/search']);
                    });

When i execute the above code, the modal is not in a blocking mode at all. it just executes the router.navigate and move to the next page, I am not able to see the modal dialog at all. I want to block the execution of the code until the user clicks the OK button.

**Comment by shlomiassaf** [comment]
`isBlocking` is a UX term only. It does not (and cant...) block code execution.

Once you call open you get a promise which resolves once the modal is shown.
So, once it is shown you navigate to a different page and it should navigate to a page.

The blocking feature is just a  UX behaviour which means if a user clicks outside of the modal don't close the modal.

If you open a modal and click refresh or change the url to a different route manually, it will also change the page regardless of isBlocking state.

If you want to prevent page transition while a modal is open you need to use `Guards` to prevent that.

You can use the overlay service to get the total amount of dialog refs open, this will allow you to create a guard that decides if a page can change only if no modals are open.
This is of course generic for all modals.

For a specific modal use a different approach, create a guard and a modal guard service, every time you create a dialog ref send it to the service. The service will keep track of the number of opened modals that block a page change.

The guard itself will also import that service and if no modals are open it will allow page changes.

**Comment by ssashok10** [comment]
Thanks for the clarification. I am closing it now.
