### ISSUE TITLE
ngModule Warning ---- Not Imported/declared

### ISSUE THREAD

**Issue by webartistkb** [shlomiassaf/angular2-modal#168]
Happening for your own plunker:
http://embed.plnkr.co/mbPzd8/

* **I'm submitting a ...**
[ *] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
A Bug

* **What is the current behavior?**
Getting below warning..
NgModule BootstrapModalModule uses BSModalContainer via "entryComponents" but it was neither declared nor imported! This warning will become an error after final.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use one of the templates above as a starting point).
This warning is coming for your own plunker as well.
http://embed.plnkr.co/mbPzd8/

* **What is the expected behavior?**
These warning need to be fixed as these will become errors after final release of angular 2.0

* **What is the motivation / use case for changing the behavior?**
Will be an error later after angular final release.

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.5 
- angular-cli": "1.0.0-beta.11-webpack.2",
- Browser: [all | Chrome - latest  | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Fix:** Simple fix is to add import statement and declare it in ngModule (app.module.ts)

**Comment by shlomiassaf** [comment]
@webartistkb Thanks.
