### ISSUE TITLE
has no exported member 'Overlay'

### ISSUE THREAD

**Issue by pepito87** [shlomiassaf/angular2-modal#169]
I am following RC5 quickthrough and have added the necessary mappings and packages to the systemjs file. Everything seems to work fine except for the overlay import statement.

I am getting the following error **has no exported member 'Overlay'**

Is there something else I'm missing?

**component.ts:**
import { Overlay } from 'angular2-modal';

**systemjs:**

'angular2-modal':             'https://npmcdn.com/angular2-modal' + angular2ModalVer

'angular2-modal':             { defaultExtension: 'js', main: 'bundles/angular2-modal.umd' }

**Comment by troyanskiy** [comment]
@pepito87 Fine for me in beta10

**Comment by shlomiassaf** [comment]
@pepito87 this is weird.

I assume you refer to a plunker since you're linking to **npmcdn**
[this plunker](https://embed.plnkr.co/mbPzd8/) is also importing `Overlay` among other things...
It's also using the UMD bundle.

since its transpiling TS at runtime we should be able to reproduce...

**Comment by pepito87** [comment]
@shlomiassaf yes following the Plunkr example. I did notice that it was referencing a cdn but it seems to be trying to hit the local index typescript file still.

**Comment by shlomiassaf** [comment]
@pepito87 I don't understand, the plunker works with no errors, so whats wrong?

**Comment by pepito87** [comment]
@shlomiassaf Im hitting the error on my app which is hosted on my machine. I've replicated the Plunkr code into my app but getting the mentioned error above. That's the exact problem! I have no idea why the plunkr code is working fine, yet my app fails, with both being the same code, versions etc..

**Comment by shlomiassaf** [comment]
@pepito87 The umd bundles does not have type definitions, especially if you import it directly from npmcdn.


I didn't try it but you could reference the main `index.d.ts` file in the package, but it will require you to install it locally.

**Comment by pepito87** [comment]
@shlomiassaf Ahh ok. I'll install locally and reference index. See how that goes.

**Comment by shlomiassaf** [comment]
I'll close this stale issue, please re-open with a comment if it still an issue.
