### ISSUE TITLE
Error on BS Custom Popup Closing

### ISSUE THREAD

**Issue by troyanskiy** [shlomiassaf/angular2-modal#170]
Hello.

I have an error when I'm closing the Custom Popup.
Seems it appear in `dialog-ref.ts` line 119 by executing `this.overlayRef.destroy()`;

The popup is closing very strange. Like it moves upper without fading and then despairs with error in console.

```
platform-browser.umd.js:937 EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in ./CSSBackdrop class CSSBackdrop_Host - inline template:0:0

Error: Error in ./CSSBackdrop class CSSBackdrop_Host - inline template:0:0
    at ViewWrappedException.WrappedException [as constructor] (http://localhost:8080/node_modules/@angular/core/bundles/core.umd.js:4489:35)
    at new ViewWrappedException (http://localhost:8080/node_modules/@angular/core/bundles/core.umd.js:8591:20)
    at DebugAppView._rethrowWithContext (http://localhost:8080/node_modules/@angular/core/bundles/core.umd.js:12708:27)
    at DebugAppView.destroyLocal (http://localhost:8080/node_modules/@angular/core/bundles/core.umd.js:12684:22)
    at DebugAppView.AppView._destroyRecurse (http://localhost:8080/node_modules/@angular/core/bundles/core.umd.js:12506:18)
    at DebugAppView.AppView._destroyRecurse (http://localhost:8080/node_modules/@angular/core/bundles/core.umd.js:12500:29)
    at DebugAppView.AppView._destroyRecurse (http://localhost:8080/node_modules/@angular/core/bundles/core.umd.js:12504:29)
    at DebugAppView.AppView.destroy (http://localhost:8080/node_modules/@angular/core/bundles/core.umd.js:12492:18)
    at ComponentRef_.destroy (http://localhost:8080/node_modules/@angular/core/bundles/core.umd.js:9013:86)
    at DialogRef._destroy (http://localhost:8080/node_modules/angular2-modal/bundles/angular2-modal.umd.js:426:29)
```

**Comment by webartistkb** [comment]
I was getting that before intermittently. Working fine now. Using Custom Modal.

**Comment by shlomiassaf** [comment]
This is most probably because of animation.
Bootstrap plugin? vex?

**Comment by webartistkb** [comment]
I got this again once after closing it. When i  tried to replicate, It didn't come...
I am using Bootstrap - Custom Modal.

browser_adapter.js:84 EXCEPTION: Error: Uncaught (in promise): undefinedBrowserDomAdapter.logError @ browser_adapter.js:84BrowserDomAdapter.logGroup @ browser_adapter.js:94ExceptionHandler.call @ exception_handler.js:65next @ application_ref.js:348schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:77onError @ ng_zone.js:124onHandleError @ ng_zone_impl.js:74ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233_loop_1 @ zone.js:487drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
browser_adapter.js:84 STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.js:84ExceptionHandler.call @ exception_handler.js:67next @ application_ref.js:348schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:77onError @ ng_zone.js:124onHandleError @ ng_zone_impl.js:74ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233_loop_1 @ zone.js:487drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
browser_adapter.js:84 Error: Uncaught (in promise): undefined
    at resolvePromise (zone.js:538)
    at PromiseCompleter.reject (zone.js:515)
    at _dismiss (dialog-ref.ts:82)
    at dialog-ref.ts:85
    at ZoneDelegate.invoke (zone.js:323)
    at Object.onInvoke (ng_zone_impl.js:53)
    at ZoneDelegate.invoke (zone.js:322)
    at Zone.run (zone.js:216)
    at zone.js:571
    at ZoneDelegate.invokeTask (zone.js:356)BrowserDomAdapter.logError @ browser_adapter.js:84ExceptionHandler.call @ exception_handler.js:68next @ application_ref.js:348schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:77onError @ ng_zone.js:124onHandleError @ ng_zone_impl.js:74ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233_loop_1 @ zone.js:487drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
zone.js:463 Error: Uncaught (in promise): undefined(…)

**Comment by shlomiassaf** [comment]
@troyanskiy please supply the custom component code + how you execute.

Also, you're not using custom plugin right? you're working on the bootstrap plugin without changes?

**Comment by shlomiassaf** [comment]
@webartistkb For "leave" animation to run the library must wait for the animation to end and only then destroy the overlay.

Since the animation module in angular 2 does not support external css animation (css not parsed by angular which means css not in `styles` or `styleUrls`)  I can't use the native angular animation for bootstrap (bootstrap animations are powered by transitions triggered by the class `in`).

To workaround it I use the `TransitionEnd` & `AnimationEnd` event.
Once it is fired I destroy the modal.

Since it might not fire for some reason I'v created a guard via a timer (1sec) that rejects if invoked.

This is plugin specific, bootstrap plugin implements it since it expects animation.

I suspect this is the reason.

**Comment by troyanskiy** [comment]
@shlomiassaf Yes. I'm working with custom component with bootstrap plugin without changes.
```ts
import {Component, AfterViewInit, OnInit, ElementRef} from '@angular/core';
import {ModalComponent, DialogRef, CloseGuard} from 'angular2-modal';
import {BSModalContext} from 'angular2-modal/plugins/bootstrap';
import {IPage, IForm, ILine, IAction} from '../../interfaces/index';
import {ActionHelper, ActionStaticService, DomHelper} from '../../helpers/index';
import {ModalService} from '../../services/modal.service';


export class PimModalComponentData extends BSModalContext {
  constructor(public data:IPimModalComponentData) {
    super();
  }
}


export interface IPimModalComponentData {
  size?:string;
  closable?:boolean;
  header?:IPage | IForm | ILine;
  body?:IPage | IForm | ILine;
  footer?:IPage | IForm | ILine;
}

@Component({
  moduleId: module.id,
  selector: 'pim-modal',
  templateUrl: 'modal.component.html'
})
export class PimModalComponent implements CloseGuard, ModalComponent<PimModalComponentData>, OnInit, AfterViewInit {

  data:IPimModalComponentData;

  private elm: Element;

  constructor(public dialog:DialogRef<PimModalComponentData>, elm: ElementRef) {

    this.data = dialog.context;
    ModalService.modalStack.push(this.dialog);
    this.dialog.setCloseGuard(this);

    this.elm = elm.nativeElement;
  }


  ngOnInit():any {
    if (!this.data) {
      this.data = {};
    }

    if (typeof this.data.closable !== 'boolean') {
      this.data.closable = true;
    }

    if (typeof this.data.size !== 'string') {
      this.data.size = 'md';
    }

    // console.log(this.data);

  }


  ngAfterViewInit():any {

    // let backDropElm = 'modal-overlay'; //'modal-backdrop'
		//
    // if (this.data.closable) {
    //   DomHelper.on(document.querySelector(backDropElm), 'click.modalBackdrop', ($event:any) => {
    //     if (!DomHelper.closest($event.target, '.modal-content')) {
    //       this.closeModal();
    //     }
    //   });
    // }
		//
    // let rootElm = DomHelper.closest(this.elm, backDropElm);
    // rootElm.querySelector('.modal-dialog').classList.add('size-' + this.data.size);
		//
    // let buttons = rootElm.querySelectorAll('.modal-content button');
    // let button:any;
    // for (let i = 0; i < buttons.length; i++) {
    //   button = buttons[i];
    //   button.className = '';
    //   button.classList.add('dark');
    // }
  }

  closeModal() {
    this.dialog.close();
  }

  beforeDismiss():boolean|Promise<boolean> {
    // console.log('beforeDismiss');
    return true;
  }

  beforeClose():boolean|Promise<boolean> {
    // console.log('beforeClose');
    // if (this.data.closable) {
    //   DomHelper.off(null, 'click.modalBackdrop');
    // }
    let index = ModalService.modalStack.indexOf(this.dialog);
    if (index > -1) {
      ModalService.modalStack.splice(index, 1);
    }
    // this.dialog.dismiss();
    return false;
  }

  footerButtonClick(event:string) {

    // console.log(event);
    if (event === 'close_dialog') {
      this.closeModal();
      return;
    }

    ActionStaticService.getAction(event)
      .then((action:IAction) => {
        this.dialog.close();
        // console.log(action);
        action.data.params = ActionHelper.getAllParams(action);
        ActionStaticService.executeAction(action);
      });
  }
}
```

Here how it calls
```ts
import {Injectable} from '@angular/core';
import {Modal, DialogRef, OverlayConfig} from 'angular2-modal';
import {BSModalContextBuilder} from 'angular2-modal/plugins/bootstrap';
import {PimModalComponent, PimModalComponentData, IPimModalComponentData} from '../components/modal/modal.component';

@Injectable()
export class ModalService {

  static modalStack: DialogRef<any>[] = [];

  private _modal: Modal;

  get modal() {
    return this._modal;
  }

  set modal(modal: Modal) {
    this._modal = modal;
  }

  page(data: IPimModalComponentData) {
    setTimeout(() => {

      const builder = new BSModalContextBuilder<PimModalComponentData>(
        <any>data,
        undefined,
        PimModalComponentData
      );

      let overlayConfig: OverlayConfig = {
        context: builder.toJSON()
      };


      this.modal.open(PimModalComponent, overlayConfig);

    }, 0);
  }

  closeAll() {
    let dialogs = ModalService.modalStack;
    ModalService.modalStack = [];
    dialogs.forEach((dialog) => {
      // console.log(dialog);
      dialog.close();
    });
  }

}

```

**Comment by troyanskiy** [comment]
@shlomiassaf any suggestions?

**Comment by troyanskiy** [comment]
@shlomiassaf I did a bit deeper debugging. It throws an Error(name:EmptyError) [here](https://github.com/shlomiassaf/angular2-modal/blob/0a82b3fa4a6819ee7befb96c1d411b4ec84a6ee0/src/components/angular2-modal/components/base-dynamic-component.ts#L86) 
When it tries to destroy CSSBackdrop component

**Comment by troyanskiy** [comment]
@shlomiassaf I have found why!
I miss css class .fade!!!

**Comment by shlomiassaf** [comment]
@troyanskiy Its very strange, the `fade` css class is already in the backdrop template.

Or, do you mean the css class was not present in the CSS file?

**Comment by troyanskiy** [comment]
@shlomiassaf yes, the class with transitions was not presented in the CSS file.
