### ISSUE TITLE
Displaying non-static content without subclassing ModalComponent?

### ISSUE THREAD

**Issue by colinmorris** [shlomiassaf/angular2-modal#172]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository

All the examples in the demo/quickthrough show modals with static HTML content. The exception is the custom modal example, which subclasses ModalComponent.

I'm wondering if there's any middle-ground if I want to use some directives in the modal content, but have no need to change the behavior of the modal (as the `AdditionCalculateWindow` example does).

Basically, I want to be able to do something like...

```
<modal size="lg" showClose="true" #modal>
    <my-custom-component>
    <my-other-custom-component>
    <p>etc.</p>
</modal>
<button (click)="modal.open()">My modal</button>
```

It seems like it's not as simple as just putting template stuff inside the strings passed to `body()` or `title()` when using one of the preset builders. The [source](https://github.com/shlomiassaf/angular2-modal/blob/master/src/components/angular2-modal/plugins/bootstrap/presets/message-modal-preset.ts#L68) mentions that "When using HTML, the template is not compiled. (binding and expression will not parse)"

But is there another way to do this? (If so, it would be great to have an example of this in the docs).

**Comment by shlomiassaf** [comment]
I'm working on a new feature for using templates and simple strings...
next release will have it

**Comment by shlomiassaf** [comment]
this is also a bit tricky, since the context (configuration) is different from plugin to plugin.

For example, the bootstrap plugin has a `dialogClass` property that default to some value, if its not present the modal will not display the way it should.

It is set by default when using the bootstrap `Modal` service however, this is different, no service here just s component which isn't plugin specific.

**Comment by shlomiassaf** [comment]
Feature was implemented

**Comment by sime** [comment]
Just to confirm the feature is in v2 of the plugin, and it is called SwapComponent?
