### ISSUE TITLE
[beta.11] No provider for Renderer

### ISSUE THREAD

**Issue by CaselIT** [shlomiassaf/angular2-modal#175]
Continuing from #174, since that issue was resolved, but this error is still present in the beta 11
See the reply from @orange4glace to reproduce it https://github.com/shlomiassaf/angular2-modal/issues/174#issuecomment-243696472

**Comment by shlomiassaf** [comment]
Will get to it, I just need to finish a PR for the angular project.

**Comment by shlomiassaf** [comment]
If anyway want's to jump in, by all means :)

**Comment by shlomiassaf** [comment]
OK guys, try `beta12` I think it's solved now, please let me know

**Comment by CaselIT** [comment]
It appears to be working. Thanks @shlomiassaf
