### ISSUE TITLE
Error on npm start. 

### ISSUE THREAD

**Issue by jremya** [shlomiassaf/angular2-modal#177]
IMPORTANT: Please provide a sample using:  

  * V1: http://plnkr.co/edit/hwbmF9?p=preview 
  * V2: http://plnkr.co/edit/7c0pGE?p=preview

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Application does not start up giving compilation errors.

node_modules/angular2-modal/angular2-modal.module.d.ts(16,50): error TS2315: Type 'Type' is not generic.
node_modules/angular2-modal/angular2-modal.module.d.ts(22,44): error TS2315: Type 'Type' is not generic.
node_modules/angular2-modal/models/tokens.d.ts(18,68): error TS2315: Type 'Type' is not generic.
node_modules/angular2-modal/overlay/overlay.component.d.ts(28,61): error TS2315: Type 'Type' is not generic.
node_modules/angular2-modal/providers/modal.d.ts(38,128): error TS2315: Type 'Type' is not generic.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use one of the templates above as a starting point).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.5
- Browser: Chrome

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by jremya** [comment]
I am trying out a demo to get the angular2 modal working. I have completed the steps as mentioned in the sample and quick guide. 
On doing an npm start, to bring the application up, I am getting the following errors.

node_modules/angular2-modal/angular2-modal.module.d.ts(16,50): error TS2315: Type 'Type' is not generic.
node_modules/angular2-modal/angular2-modal.module.d.ts(22,44): error TS2315: Type 'Type' is not generic.
node_modules/angular2-modal/models/tokens.d.ts(18,68): error TS2315: Type 'Type' is not generic.
node_modules/angular2-modal/overlay/overlay.component.d.ts(28,61): error TS2315: Type 'Type' is not generic.
node_modules/angular2-modal/providers/modal.d.ts(38,128): error TS2315: Type 'Type' is not generic.

**Comment by helzgate** [comment]
Look in those files that reference Type and change `Type<any>` to just `Type`, this will remove the errors.

**Comment by shlomiassaf** [comment]
@helzgate is right.

Use latest version and angular 2 final
