### ISSUE TITLE
DI exception when demo component recreated as service

### ISSUE THREAD

**Issue by zarkosusnjar** [shlomiassaf/angular2-modal#18]
When I move demoPage component code into service, DI fix doesn't work anymore. I get 
EXCEPTION: No provider for Modal! (Dashboard-> ModalService -> Modal)

Code is the same just instead of component I've put:

@Injectable()
export class ModalService {

Bootstrapped this service along with dozen others which work without problems.

I'm not sure how ResolvedBinding patch works, maybe I need to move bindings one level up, to the component which calls service?

**Comment by sunnyque** [comment]
Do you bootstrap Modal for app (bootstrap(App, [... ROUTER_PROVIDERS .. Modal)? Also it must be included in App Component providers: [... Modal], There must be no trouble of using modal from service but sure you missed something

**Comment by zarkosusnjar** [comment]
Yes, f course i tried to provide those in bootstrap:

```
  provide(ModalConfig, {useValue: new ModalConfig('lg', true, 81)}),
  provide(Modal, {useValue : Modal }),
  provide(ElementRef, {useValue: ElementRef}), //needed because of: EXCEPTION: No provider for ElementRef! (Newsletters -> ModalService -> ElementRef)
```

But when I clear DI excpetions, I get this:

```
EXCEPTION: Error during evaluation of "click"
...
 ORIGINAL EXCEPTION: TypeError: this.modal.open is not a function
```

**Comment by zarkosusnjar** [comment]
Got it, basically I needed to put Modal and ElementRef without provide function. Now it works when provided like this:

```javascript
...
provide(ModalConfig, {useValue: new ModalConfig('lg', true, 81)}),
  Modal,
  ElementRef,
  ModalService
...
```
Example service would be very helpful in demo. I guess everyone who makes SPA will make this as service instead of duplicating dozens of lines of code in each component they need modal in.

**Comment by rsnider19** [comment]
@zarkosusnjar can you post your working modal service?
