### ISSUE TITLE
Angular RC5 - Big Binding Bug

### ISSUE THREAD

**Issue by Ivandolchevic** [shlomiassaf/angular2-modal#180]
Hello,

* **I'm submitting a ...**
[* ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
*bug*

* **What is the current behavior?**
A binded component with a simple `*ngFor` doesn't react to non-human events. 

### Here is the binded component List
```
@Component({
    selector:'list',
    template:`
        <div>
             <div *ngFor="let element of elements; let i=index">{{element}}</div>
        </div>
    `
})

export class List{
    @Input() list;
}
```
### HTML
```
<div>
<list [elements]="elements"></list>
</div>

### Typescript
export class Stats {
    likeServices;
    likesServicesSubscriptionGet;
    elements;

    constructor(@Inject(LikeServices) _likeServices:LikeServices){
        this.likeServices = _likeServices;
    }

    ngOnInit(){
        this.likesServicesSubscriptionGet = this.likeServices.data_ready
            .subscribe(
                data => {
                    this.update();
                });
    }

    update(){
        console.debug("updating");
        this.elements= this.likeServices.getAll();
        console.debug(this.elements);
    }
}
```

When I execute, I can view "updating" and I can see all the elements of my collection in the console log. BUT nothing is displayed. 

And now, if I do the following thing in my HTML
```
<div (click)="update()">
<list [elements]="elements"></list>
</div>
```
My elements are displayed if I click. 
That's work only with a human action ! :/

- Angular version: 2 RC5
- Browser: [all ]

**Comment by shlomiassaf** [comment]
@Ivandolchevic Hi, sorry I missed this issue.

I don't see a connection to the `angular2-modal` library here, seems like a generic angular 2 support question. You might get better response in the angular 2 gitter room.

Also, try using the new 2.0.0 version with angular 2 final support.

If the issue is related to the modal library please open a new issue and try to provide an example with the relevant parts to the library.

Thanks.
