### ISSUE TITLE
DefaultViewContainer, why does it exist?

### ISSUE THREAD

**Issue by orange4glace** [shlomiassaf/angular2-modal#185]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ & ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
bug?

* **What is the current behavior?**
Whatever defaultViewContainer will be, the modal is appended to body element.

* **What is the expected behavior?**
a modal element should be appended to a native element of default view container.

**Comment by shlomiassaf** [comment]
This is how angular works.
Since a modal needs a view container and a modal is not part of the template it is required.

You can set it programatically or in a template.

See [this example](https://github.com/shlomiassaf/angular2-modal/blob/master/src/demo/app/app.html#L1)
