### ISSUE TITLE
"npm run start" failed

### ISSUE THREAD

**Issue by greengalaxy2016** [shlomiassaf/angular2-modal#186]
$ npm run start

> angular2-modal@2.0.0-beta.12 start /home/hluo/git-projects/tutorials/angular2-modal
> npm run server:dev

> angular2-modal@2.0.0-beta.12 server:dev /home/hluo/git-projects/tutorials/angular2-modal
> webpack-dev-server --config config/webpack.dev.js --progress --profile --colors --watch --display-error-details --display-cached --content-base src/

  0% compileError: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server._listen2 (net.js:1239:14)
    at listen (net.js:1275:10)
    at net.js:1384:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)

npm ERR! Linux 2.6.32-504.8.1.el6.x86_64
npm ERR! argv "/clientdata/apps/node-v5.9.0-linux-x64/bin/node" "/clientdata/apps/node-v5.9.0-linux-x64/bin/npm" "run" "server:dev"
npm ERR! node v5.9.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-modal@2.0.0-beta.12 server:dev: `webpack-dev-server --config config/webpack.dev.js --progress --profile --colors --watch --display-error-details --display-cached --content-base src/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-modal@2.0.0-beta.12 server:dev script 'webpack-dev-server --config config/webpack.dev.js --progress --profile --colors --watch --display-error-details --display-cached --content-base src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-modal package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --config config/webpack.dev.js --progress --profile --colors --watch --display-error-details --display-cached --content-base src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-modal
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-modal
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hluo/git-projects/tutorials/angular2-modal/npm-debug.log

npm ERR! Linux 2.6.32-504.8.1.el6.x86_64
npm ERR! argv "/clientdata/apps/node-v5.9.0-linux-x64/bin/node" "/clientdata/apps/node-v5.9.0-linux-x64/bin/npm" "run" "start"
npm ERR! node v5.9.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-modal@2.0.0-beta.12 start: `npm run server:dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-modal@2.0.0-beta.12 start script 'npm run server:dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-modal package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run server:dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-modal
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-modal
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hluo/git-projects/tutorials/angular2-modal/npm-debug.log

**Comment by greengalaxy2016** [comment]
URL I followed to build and run the demo: https://github.com/shlomiassaf/angular2-modal

**Comment by greengalaxy2016** [comment]
npm install angular2-modal --save also failed. attached the log file
[npm-debug.log.txt](https://github.com/shlomiassaf/angular2-modal/files/467893/npm-debug.log.txt)

**Comment by shlomiassaf** [comment]
@greengalaxy2016 

You already have a server running on the port angular2-modal uses for development.

It's in the error:
` listen EADDRINUSE 127.0.0.1:8080`

EADDRINUSE = Error Address in use
