### ISSUE TITLE
upgrade to angular 2 rc7

### ISSUE THREAD

**Issue by nexus-uw** [shlomiassaf/angular2-modal#190]
rc7 was just released earlier today: https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc7-2016-09-13

**Comment by nadavsinai** [comment]
2.0 released... can we please have a working 1.x version for this?

**Comment by shlomiassaf** [comment]
Upgraded to Final.

@nadavsinai I don't have the resources to maintain 1.x, If you would like to make a PR I will be happy to accept
