### ISSUE TITLE
Unable to get custom modal to work

### ISSUE THREAD

**Issue by chungtinhlakho** [shlomiassaf/angular2-modal#191]
I followed your plnkr example exactly.  Got the alert to work but not the custom.
http://plnkr.co/edit/NiWLyRRuY6EfTV40fuTu?p=preview

In the plnkr example, it has `entryComponents: [ AdditionCalculateWindow ]` in the module and the AdditionCalculateWindow was never in the imports array of @NgModule.  If i do that I get this error:

Unhandled Promise rejection: Component AdditionCalculateWindow is not part of any NgModule or the module has not been imported into your module. ; Zone: <root> ; Task: Promise.then ; Value:
Error: Component AdditionCalculateWindow is not part of any NgModule or the module has not been imported into your module.
	

RuntimeCompiler</RuntimeCompiler.prototype._assertComponentKnown@http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:16856:1
RuntimeCompiler</RuntimeCompiler.prototype._assertComponentLoaded@http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:16862:34
RuntimeCompiler</RuntimeCompiler.prototype._compileTemplate/viewCompMetas<@http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:16878:92
RuntimeCompiler</RuntimeCompiler.prototype._compileTemplate@http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:16878:31....

I then added to the imports array, i don't get any errors on startup
`imports:      [ BrowserModule,ModalModule.forRoot(),BootstrapModalModule ],`

However, once i clicked on the customer popup to open,  I get this: 
EXCEPTION: Uncaught (in promise): TypeError: config.context is undefined
	

this._console.error("EXCEPTION: " + this._extractMessage(error));

core.umd.js (line 5995)
ORIGINAL STACKTRACE:
	

this._console.error('ORIGINAL STACKTRACE:');

core.umd.js (line 6000)
resolvePromise@http://localhost:3000/node_modules/zone.js/dist/zone.js:418:31
ZoneAwarePromise.reject@http://localhost:3000/node_modules/zone.js/dist/zone.js:477:20
Modal.prototype.open@http://localhost:3000/node_modules/angular2-modal/bundles/angular2-modal.umd.js:1361:24
.execute/AppComponent</AppComponent.prototype.openCustom@http://localhost:3000/build/app.component.js:45:21
anonymous/_View_AppComponent0.prototype._handle_click_6_0@AppComponent.ngfactory.js:63:15
DebugAppView</DebugAppView.prototype.eventHandler/<@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12193:28
decoratePreventDefault/<@http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:1854:40
DomEventsPlugin</DomEventsPlugin.prototype.addEventListener/outsideHandler/<@http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:1967:115
ZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:192:19
NgZoneImpl/this.inner<.onInvoke@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:8772:36
ZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:191:19
Zone.prototype.runGuarded@http://localhost:3000/node_modules/zone.js/dist/zone.js:99:28
NgZoneImpl</NgZoneImpl.prototype.runInnerGuarded@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:8805:71
NgZone</NgZone.prototype.runGuarded@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:9038:62
DomEventsPlugin</DomEventsPlugin.prototype.addEventListener/outsideHandler@http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:1967:78
ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:225:23
Zone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:125:28
ZoneTask/this.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:293:28
	

this._console.error(originalStack);

core.umd.js (line 6001)

Everything else looks like the example

**Comment by Luke265** [comment]
I've had same problem. You can fix this by editing "angular2-modal/overlay/overlay-service.js:83" change 
`!!config.context.inElement` to `config.context ? config.context.inElement : false`.

**Comment by chungtinhlakho** [comment]
have this been pull?

**Comment by shlomiassaf** [comment]
@chungtinhlakho Check the new version, it is fixed now.

Thanks.
