### ISSUE TITLE
Type 'Type' is not generic in angular2-modal.module.d.ts

### ISSUE THREAD

**Issue by rahuldev761** [shlomiassaf/angular2-modal#197]
IMPORTANT: Please provide a sample using:  

  * V1: http://plnkr.co/edit/hwbmF9?p=preview 
  * V2: http://plnkr.co/edit/7c0pGE?p=preview

* **I'm submitting a ...**
[ *] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
     bug report

* **What is the current behavior?**
     [default] /home/rahul/Documents/codebase/dcnweb/node_modules/angular2-modal/angular2-modal.module.d.ts:16:50 
    Type 'Type' is not generic.
[default] /home/rahul/Documents/codebase/dcnweb/node_modules/angular2-modal/angular2-modal.module.d.ts:22:44 
    Type 'Type' is not generic.
[default] /home/rahul/Documents/codebase/dcnweb/node_modules/angular2-modal/models/tokens.d.ts:18:68 
    Type 'Type' is not generic.
[default] /home/rahul/Documents/codebase/dcnweb/node_modules/angular2-modal/overlay/overlay.component.d.ts:28:61 
    Type 'Type' is not generic.
[default] /home/rahul/Documents/codebase/dcnweb/node_modules/angular2-modal/providers/modal.d.ts:38:128 
    Type 'Type' is not generic.
[default] Checking finished with 5 errors

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use one of the templates above as a starting point).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by shlomiassaf** [comment]
Use angular final.

Next time try to spare a minute and write a description and not just paste the error...
