### ISSUE TITLE
Documentation for using VEX Modal

### ISSUE THREAD

**Issue by GopalakrishnanKandasamy** [shlomiassaf/angular2-modal#198]
HI, I've been struggling to implement VEX modal into my angular2 app. Its not as easy as Bootstrap. It will be great if you provide a documentation of how to use it or an example. Thanks.

**Comment by shlomiassaf** [comment]
I'm limited in time, I would love if someone can help setting doc's up.

Anyway, post the errors and me or other developers might help

**Comment by GopalakrishnanKandasamy** [comment]
I'm pretty comfortable now. There was no error but i was unable to know how to use.
