### ISSUE TITLE
Error : Failed to load resource bootstrap.js ( Version : "2.0.0-beta.13" )

### ISSUE THREAD

**Issue by ssashok10** [shlomiassaf/angular2-modal#201]
I recently migrated my code from "2.0.0-beta.9" to "2.0.0-beta.13" and started seeing the below error,

http://localhost/node_modules/angular2-modal/plugins/bootstrap.js Failed to load resource: the server responded with a status of 404 (Not Found)

I have checked the installation folder "node_modules\angular2-modal\plugins\bootstrap" and not seeing any bootstrap.js file there...I am using custom modal dialog and the same code works fine with "2.0.0-beta.9".  Is there any sample application that i can refer to implement  "2.0.0-beta.13"? I am using Angular 2.0.0

**Comment by shlomiassaf** [comment]
I can't really guess what happens.

Is it SystemJS, webpack? cli?

**Comment by ssashok10** [comment]
This is SystemJS. I certainly don't see the file "bootstrap.js" on the installation folder. Instead i see "bootstrap.module.js". Is there anything changed on " "2.0.0-beta.13"".  Can you please provide any working sample for the latest version?

**Comment by shlomiassaf** [comment]
[This plunker](http://plnkr.co/edit/7c0pGE?p=preview) is based on SystemJS.
You need to tell SystemJS what file to load then you import `angular2-modal/plugins/bootstrap`
by default it just adds `.js`

See the plunker and the systemjs config file.

This is not an angular2-modal issue, its SystemJS configuration... 

I don't have the time to support that, you'll have to dig and understand SystemJS if you want to use it.

Personally, I would stay away from it, you will spend hours on such issues.

**Comment by ssashok10** [comment]
I am able to fix the issue and found out one breaking change with Angular 2.0.0 and Angular modal 2.0.0-beta.13.  The custom modal has to be added with "declarations" section of angular modules file in addition to add it with "entryComponents".  By the way, the original error that i posted went away after adding the following entry on "systemjs.config.js".

'angular2-modal/plugins/bootstrap': { defaultExtension: 'js', main: 'index' }

Hope this will help someone too.

**Comment by jwood803** [comment]
I had a similar problem. For some reason SystemJS didn't like the way I did it with mapping the individual files way. Once I switched to using the UMD way, as shown in the Plunkr, it works just fine.

Basically, SystemJS is weird...

**Comment by ssashok10** [comment]
Yes. You are right about SystemJS. I changed my application with WebPack now and it works lot better than SystemJS

**Comment by ashwinirajput** [comment]
Same problem can any one help me 
 (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/node_modules/angular2-modal/plugins/bootstrap.js
->System.config.js issue i try from above plunker but not heplful

**Comment by ashwinirajput** [comment]
I recently migrated my code from "2.0.0-beta.9" to "2.0.0-beta.13" and started seeing the below error, how we know my version in cmd

**Comment by ssashok10** [comment]
**Please get away from SystemJS**.  Your application can not be deployed into the production environment with the "SystemJS" loader as the initial loading time is too high. WebPack or the Rollup utility are powerful and its easy to work with in the long run. If you can not move with WebPack/Rollup utility at this moment, try deleting the "angular2-modal" folder manually and import it again. Hope this helps.

**Comment by ashwinirajput** [comment]
I am new in angular 2 how I move to Webpack or Rollup utility.
Please Help or provide me some link

**Comment by jwood803** [comment]
@ashwinirajput I think the [`angular2-cli`](https://github.com/angular/angular-cli) uses webpack. If you're not too far in your application you can use that to create the seed for your app.
