### ISSUE TITLE
Support angular 2.0.1

### ISSUE THREAD

**Issue by JulioC** [shlomiassaf/angular2-modal#204]
Angular 2.0.1 [is out](https://github.com/angular/angular/blob/master/CHANGELOG.md). There is nothing broken on this project, but it depends on "2.0.0" so npm complains about it.

[Angular team said](http://angularjs.blogspot.com.br/2016/09/angular2-final.html) they will use semver from now on (I hope they keep their word), so I think it's safe to use "~2.0.0" now.

**Comment by shlomiassaf** [comment]
Will do, a little swamped now but I want to release something soon, with some features like AOT and stuff.

Will update.

**Comment by JulioC** [comment]
Sorry, miss clicked on the close button
