### ISSUE TITLE
dialogClass is type of FluentAssignMethod<BootstrapModalSize, this>

### ISSUE THREAD

**Issue by bittergeek** [shlomiassaf/angular2-modal#205]
In BSModalContextBuilder, dialogClass is type of FluentAssignMethod<BootstrapModalSize, this> while size is type of FluentAssignMethod<string, this>. This looks wrong. I'm getting compilation error trying to set a custom class on the dialog:
```
this.modal.prompt()
      .size('lg')
      .isBlocking(true)
      .keyboard(27)
      .dialogClass('modal-dialog')
      .title(title)
      .body(message)
      .open().then(this.setFocus);
```

**Comment by shlomiassaf** [comment]
Yes, you are right!!! thanks!
