### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by rsnider19** [shlomiassaf/angular2-modal#21]
I am trying to incorporate this into an existing project. I did an `npm install angular2-modal` and then referenced `<script src="node_modules/angular2-modal/dist/angular2-modal.js"></script>` in my index.html file. When running my project, I am getting `required is not defined`. Am I missing something here?

**Comment by shlomiassaf** [comment]
It's a CommonJs module in ES5 so it requires using a CommonJS loader or bundled (e.g webpack).

I didn't find the time to incorporate a regular build as I figured most developers will not need it.

If anyone wants to submit a PR please do.

**Comment by ogalimov** [comment]
The problem is: If I understand correctly they do this in the Angular 2 tutorial. So a person, who just finished the tutorial (like me) can't use your lib.

**Comment by nosachamos** [comment]
+1 to this issue

**Comment by AbdulRahmanAlHamali** [comment]
+1 for this issue

**Comment by shlomiassaf** [comment]
You can now use SystemJS or any CommonJS bundler.
