### ISSUE TITLE
 modal.defaultViewContainer does not exist on Modal

### ISSUE THREAD

**Issue by chungtinhlakho** [shlomiassaf/angular2-modal#210]
Using with angular 2.0, 

if i don't set the defaulViewContainer, i get this error

app.bundle.js (line 30818)
Error: Uncaught (in promise): Error: Default view container not set. Add the "defaultOverlayTarget" directive to the application root component template (e.g: <span defaultOverlayTarget></span>. You can also set it manually using the "Overlay" service "defaultViewContainer" property.

any help is much appreciate it.

**Comment by shlomiassaf** [comment]
You have it in the error.
Anyway, in you root template add this
```
<span defaultOverlayTarget></span>
```
It will solve the issue.

**Comment by VuongTran21** [comment]
Hi @shlomiassaf ,
Thanks for your nice angular 2 modal.
While using, I got an error the same with @chungtinhlakho 's issue. I used your way to fix but problem can not be resolved, is there any else way to do?

**Comment by MartinHarkins** [comment]
@VuongTran21 

The `defaultViewContainer` property is on the `modal.overlay` object:
```
constructor(vcRef: ViewContainerRef, public modal: Modal) {
    modal.overlay.defaultViewContainer = vcRef;
}
```

**Comment by singhnar** [comment]
I am getting below error while using ngx-modialog

ERROR TypeError: __WEBPACK_IMPORTED_MODULE_0__angular_core__.H.create is not a function
    at DOMOverlayRenderer.render (ngx-modialog.es5.js:1389)
    at Overlay.createOverlay (ngx-modialog.es5.js:1347)
    at ngx-modialog.es5.js:1329
    at Array.map (<anonymous>)
    at Overlay.open (ngx-modialog.es5.js:1329)
    at Modal$$1.Modal.open (ngx-modialog.es5.js:1462)
    at OneButtonPresetBuilder.ModalOpenContextBuilder.open (ngx-modialog.es5.js:1794)
    at AppComponent.webpackJsonp.114.AppComponent.onClick (app.component.ts:32)
    at Object.eval [as handleEvent] (AppComponent.html:1)
    at handleEvent (core.es5.js:11997)

Any help on this error is much appreciated. 

My code 

app.component.ts

import { Component, ViewContainerRef } from '@angular/core';
import { Overlay } from 'ngx-modialog';
import { Modal } from 'ngx-modialog/plugins/bootstrap';

@Component({
  selector: 'app-root',
  template: `<button (click)="onClick()">Alert</button>`
})

export class AppComponent {
  constructor(public modal: Modal) {
  }

  onClick() {
   console.log(this.modal);
    const dialogRef = this.modal.alert()
        .size('lg')
        .showClose(true)
        .title('A simple Alert style modal window')
        .body(`
            <h4>Alert is a classic (title/body/footer) 1 button modal window that
            does not block.</h4>
            <b>Configuration:</b>
            <ul>
                <li>Non blocking (click anywhere outside to dismiss)</li>
                <li>Size large</li>
                <li>Dismissed with default keyboard key (ESC)</li>
                <li>Close wth button click</li>
                <li>HTML content</li>
            </ul>`)
        .open();

    dialogRef.result
        .then( result => alert(`The result is: ${result}`) );
  }
}

app.module.ts

@NgModule({
  declarations: [ ],
  imports: [
    ModalModule.forRoot(),
    BootstrapModalModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
