### ISSUE TITLE
error loading after update to 2.0

### ISSUE THREAD

**Issue by lucamorelli** [shlomiassaf/angular2-modal#214]
I updated to 2.0 and now I receive this error:

(index):32 Error: SyntaxError: Unexpected token <
	Evaluating http://localhost:5000/traceur
	Error loading http://localhost:5000/traceur
	Error loading http://localhost:5000/libs/angular2-modal/plugins/bootstrap/index.js as "angular2-modal/plugins/bootstrap" from http://localhost:5000/app/app.module.js

how can I solve it?

**Comment by shlomiassaf** [comment]
What is your setup? Never tested against traceur

**Comment by lucamorelli** [comment]
it's an asp.net core application using typescript and system.js. which informations do you need? honestly I don't know why uses traceur

**Comment by shlomiassaf** [comment]
It seems like you are using some old setup or non mainstream version of a typescript compilation process, probably runtime.

`traceur` is a javascript to javascript compiler. Looking at the error it has problem dealing with the library output which is ES6, this seems to be an configuration thing in traceur I believe.

I don't know much about it...

Anyway, the package also has es5 UMD bundle in the bundles directory, you can try and load it.

**Comment by lucamorelli** [comment]
hmm ... II'm using ts 2.0.3 installed using the tools installer for vs. I'll try with the bundle

**Comment by shlomiassaf** [comment]
Fixed in 2.0.1

Same as #216 , please track progress there.
