### ISSUE TITLE
http://localhost:5555/node_modules/angular2-modal/plugins/bootstrap.js Failed to load resource: the server responded with a status of 404 

### ISSUE THREAD

**Issue by tonychangcheng** [shlomiassaf/angular2-modal#231]
Hi, 

I just upgraded the latest Angular2-seed project and Angular2-modal. And I got the below error when starting the server. Anyone has the same issue? 
"http://localhost:5555/node_modules/angular2-modal/plugins/bootstrap.js Failed to load resource: the server responded with a status of 404 "

Regards
Cheng

**Comment by markfranco** [comment]
I also have the same issue

**Comment by tonychangcheng** [comment]
I just fixed the issue by adding below to the /tools/config/seed.config.ts

     'angular2-modal': 'node_modules/angular2-modal/bundles/angular2-modal.umd.js',
     'angular2-modal/plugins/bootstrap': 'node_modules/angular2-modal/bundles/angular2-modal.bootstrap.umd.js',
