### ISSUE TITLE
Allow inner HTML inside modal body

### ISSUE THREAD

**Issue by danbachar** [shlomiassaf/angular2-modal#233]
I'm submitting a 
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

What is the current behavior?
When generating a custom modal through the online bootstrap modal generator, 
enter `<input type="text" placeholder="test" />` in the "Body" section, like so: 
`modal.alert()
    .size('lg')
    .isBlocking(true)
    .showClose(true)
    .keyboard(27)
    .title('Hello World')
    .body('<input type="text" placeholder="test" />')
    .open();`

What is the expected behavior?
You should be able to have complex HTML elements and only not plain-text.

What is the motivation / use case for changing the behavior?
You could use complex HTML elements and not solely plain-text; forms, etc.

Please tell us about your environment:
Just open http://shlomiassaf.github.io/angular2-modal/#/bootstrap-demo/customizeModals
on Chrome.

**Comment by avoliva** [comment]
Has to do with this https://angular.io/docs/ts/latest/guide/security.html#!#xss

**Comment by shlomiassaf** [comment]
Adding HTML is blocked by the framework.
