### ISSUE TITLE
Insert in the modal body another custom component

### ISSUE THREAD

**Issue by baio** [shlomiassaf/angular2-modal#234]
feature request / question

Hi Is there some possibility to use fluent api and insert in the body another component, like so:

```
  import { SomeConentComponent } from '.../..'
...

   modal.prompt()
    .title('Hello World')
    .body(SomeConentComponent)
    .open();
```

If not what is the suggested way to insert in modal body, some existent component ?

Basically my idea is to have service (not component), to which you could pass just the component for body of the modal. 

Thanks

**Comment by shlomiassaf** [comment]
Same as #242
