### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by TomaszScisloGS** [shlomiassaf/angular2-modal#241]
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

The newest version with Angular2 2.0.0 final throws an error after importing

`index.js:7Uncaught SyntaxError: Unexpected token export`

Apparently those exports are the problem:
export { BSModalContext, BSModalContextBuilder } from './modal-context';

**Comment by sculeb** [comment]
Check out https://github.com/shlomiassaf/angular2-modal/issues/220#issuecomment-254313943
Solved it for me.

**Comment by MrDaande** [comment]
I have the same error but on another position.
I'm using Meteor 1.4.2 with angular/core@2.1.2 and get the following error:

`Uncaught SyntaxError: Unexpected token export` at `collection.ts:359`

![bildschirmfoto 2016-10-28 um 00 14 46](https://cloud.githubusercontent.com/assets/8028977/19787563/ab946ed8-9ca3-11e6-94a9-6b977345ff7a.png)

This are the dependecies from my package.json

`
"dependencies": {
    "@angular/common": "2.1.2",
    "@angular/compiler": "2.1.2",
    "@angular/core": "2.1.2",
    "@angular/forms": "2.1.2",
    "@angular/http": "^2.0.0",
    "@angular/material": "^2.0.0-alpha.9-3",
    "@angular/platform-browser": "2.1.2",
    "@angular/platform-browser-dynamic": "2.1.2",
    "@angular/router": "3.1.2",
    "angular2": "^2.0.0-beta.17",
    "angular2-meteor": "0.7.0",
    "angular2-meteor-polyfills": "0.1.1",
    "angular2-meteor-tests-polyfills": "0.0.2",
    "angular2-modal": "^2.0.1",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "meteor-node-stubs": "0.2.3",
    "meteor-rxjs": "0.4.0",
    "meteor-typings": "^1.3.0",
    "ng2-dnd": "^2.0.1",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.40",
    "zone.js": "^0.6.26"
  }
`

**Comment by shlomiassaf** [comment]
Consolidated in #244, please come help and replay there.
