### ISSUE TITLE
Dialog.context is empty after upgrading to v2.0.1

### ISSUE THREAD

**Issue by nkagarw** [shlomiassaf/angular2-modal#245]
**bug**
In version 2.0.1, dialog.context is an empty object instead of containing inputs from parent.
Please see the updated plunker showing the bug here : https://plnkr.co/edit/UGvE5jDc6onGh8KToAOw?p=preview

I only made 2 changes to the existing plunker : 
1. Changed from @1.1.5 to @2.0.1 in line 13 of systemjs.config.js
2. Added `<span defaultOverlayTarget></span>` at line 8 of app.component.ts

Now when I click on the custom modal button, the dialog says "I received an injection of the <missing> number and the <missing> number" instead of "I received an injection of the number **2** and the number **3**"

In the constructor of custom-model-sample.ts - dialog.context is an empty object.

**Comment by Luke265** [comment]
Not sure if this is a bug, but replace `this.modal.open(AdditionCalculateWindow, new AdditionCalculateWindowData(2, 3));` with `this.modal.open(AdditionCalculateWindow, {context: new AdditionCalculateWindowData(2, 3)});`

**Comment by nkagarw** [comment]
Thanks Luke. it's working.
