### ISSUE TITLE
[question] Should the modal dismiss automatically when clicking outside of it ?

### ISSUE THREAD

**Issue by lordpiti** [shlomiassaf/angular2-modal#250]
Just tried to click outside of the modal after opening it but it doesn't close this way. It does when pressing ESC key though.

I create the modal this way : 
`this.modal.open(CreateEditPressModal, overlayConfigFactory({ pressItem: pressItem, mediaOutletBlogTypes: this.MediaOutletBlogTypes }, BSModalContext));`

Is this the normal behaviour and if so, how can i set up the modal so that it closes when clicking outside of it ?

**Comment by animator013** [comment]
BSModalContext interface has isBlocking field. Maybe setting it to false like this could help:

`this.modal.open(CreateEditPressModal, overlayConfigFactory({ isBlocking: false, pressItem: pressItem, mediaOutletBlogTypes: this.MediaOutletBlogTypes }, BSModalContext));`

**Comment by lordpiti** [comment]
Thanks animator013 that was it!

**Comment by conqsys** [comment]
openPurchaseModal() {
    const builder = new BSModalContextBuilder<InvoiceEntryPurchaseModalContext>(
      { num1: 2, num2: 3 } as any,
      undefined,
      InvoiceEntryPurchaseModalContext
    );

    let overlayConfig: OverlayConfig = {
      context: builder.toJSON()
    };

    const dialog = this.modal.open(InvoiceEntryPurchaseComponent, overlayConfig({isBlocking: false}));
    dialog.then((resultPromise) => {
      return resultPromise.result.then((result) => {
        // alert(result.status);
        if (result != null) {
          this.GetSelectedPurchaseOrder(result);
        }
      }, () => console.log(' Error In Purchase modal '));
    });


  }


 const dialog = this.modal.open(InvoiceEntryPurchaseComponent, overlayConfig({isBlocking: false}));

I'm using like that getting error
 [ts] 
Cannot invoke an expression whose type lacks a call signature.
(property) isBlocking: boolean
