### ISSUE TITLE
can't load custom modal component in angular 2.1

### ISSUE THREAD

**Issue by m3l7** [shlomiassaf/angular2-modal#254]
I'm using angular 2.1 and angular 2.1 fails to load the custom AdditionCalculateWindow.

See this plunker: http://plnkr.co/edit/QK7axXrORMp8LQM3Vax9?p=preview

**Comment by clipfert** [comment]
I am also having the same issue.

**Comment by shlomiassaf** [comment]
You've upgrade to angular 2.1 in the plunker but didn't update the `Zone` library.
Angular 2.1 requires zone 6.21

set this in the **index.html**
```
<script src="https://npmcdn.com/zone.js@0.6.21?main=browser"></script>
```
