### ISSUE TITLE
[question] Does this support using the templateUrl attribute in custom modal dialogs

### ISSUE THREAD

**Issue by markperry** [shlomiassaf/angular2-modal#256]
I have a created a custom modal dialog, mostly it works fine. However, when I try to put the dialog in a .html file and use templateUrl attribute the dialog doesn't load.

This version seems to work...
@Component({
    selector: 'modal-content',
    template: '&lt;h2&gt;Here is a line of content for the dialog&lt;/h2&gt;'
})

When I put the content into a .html file this doesn't work...
@Component({
    selector: 'modal-content',
    templateUrl: './dialog-content.component.html'
})

I have double checked the path of the html file and no other changes are made betwene it working and not working.
Am I doing something or is the templateUrl attribute not supported?

Thanks

**Comment by shlomiassaf** [comment]
I can't tell, not really related to angular2-modal.

Depends on you bundler, compiler and lots of other stuff...
