### ISSUE TITLE
Provide component by name for a custom modal

### ISSUE THREAD

**Issue by rhegner** [shlomiassaf/angular2-modal#257]
Let's say I have something like this to open a custom modal:

`this.modal.open(MyComponent, overlayConfigFactory(new MyContext(7), BSModalContext));`

In my real application which component should be displayed in the modal is decided at runtime and I need the ability to open a modal with a _component name_ (which means I have the name of the component as a string).

I tried things like these but none of these work:

`this.modal.open(this["MyComponent"], overlayConfigFactory(new MyContext(7), BSModalContext));`

`this.modal.open(eval("MyComponent"), overlayConfigFactory(new MyContext(7), BSModalContext));`

How can this be done?

**Comment by shlomiassaf** [comment]
This is not related to `angular2-modal`.

Never do `eval("MyComponent")`, aside from it having no logic, eval is not a smart move.

You need to get a component, you can use a string.
If you need to get a component dynamically use a function and return it.

There is no registry mechanizem in angular that can retrieve a component by name.
The name is not how a component is identified.
