### ISSUE TITLE
Consider returning Observable instead of Promise

### ISSUE THREAD

**Issue by brian428** [shlomiassaf/angular2-modal#26]
Since most asyc-related methods in Angular 2 return or work with Observables, you might consider having Modal return an Observable instead of a Promise (for consistency)?

**Comment by shlomiassaf** [comment]
Angular's API for interacting with UI elements is using Promises, once they will change their implementation I will be able to do so as well.

See [source code](https://github.com/angular/angular/blob/a7e9bc97f6a19a2b47b962bd021cb91346a44baa/modules/angular2/src/core/linker/dynamic_component_loader.ts#L237-L239)
