### ISSUE TITLE
No component factory found for Component for angular2-modal

### ISSUE THREAD

**Issue by vijender1256** [shlomiassaf/angular2-modal#260]
I am trying to Implement Angular2-modal with angular version 2.0.1 version. The moment I change the angular version to latest which is 2.0.1 i getting below error:

![image](https://cloud.githubusercontent.com/assets/12258728/20798952/ad654d42-b7ae-11e6-8c92-19a62de22e50.png)

Below is the plunker:

https://plnkr.co/edit/ZeRajGkGwyvKRIZkG4XQ?p=preview

Seems like its an issue with angular2-modal, can anyone fix this ?

**Comment by konuch** [comment]
Could be a duplicate of #248

**Comment by shlomiassaf** [comment]
Indeed.
