### ISSUE TITLE
/node_modules/angular2-modal/plugins/bootstrap.js not found

### ISSUE THREAD

**Issue by adrianmui** [shlomiassaf/angular2-modal#266]
Just wondering if that's the proper behavior? I'm importing angular2-modal with npm and it's getting errors because it's looking for bootstrap.js in plugins/ when it should be looking at plugins/bootstrap

**Comment by ashwinirajput** [comment]
error (404 Not Found) loading http://localhost:3002/node_modules/angular2-modal/plugins/bootstrap.js

**Comment by ws-gianni** [comment]
I've the same problem : (404 Not Found) loading ........
I also configured:

**systemjs.config.js**
map {
   'angular2-modal': 'npm:angular2-modal'
},
packages: {
   'angular2-modal': {
        defaultExtension: 'js'
      }
}

**Comment by ws-gianni** [comment]
I've resolved.

systemjs.config.js:

map: {
      'angular2-modal': 'npm:angular2-modal',
      'angular2-modal/plugins/bootstrap': '/node_modules/angular2-modal/bundles'
}

packages: {
   'angular2-modal': {
        main: 'bundles/angular2-modal.umd',
        defaultExtension: 'js',
    },
    'angular2-modal/plugins/bootstrap': {
        main: 'angular2-modal.bootstrap.umd',
        defaultExtension: 'js'
    }
}

**Comment by shlomiassaf** [comment]
Seems like it's solved.
Open a new issue if not.

**Comment by ws-gianni** [comment]
I'm using v2.3.1

**Comment by ashwinirajput** [comment]
thanks, I also solved it

    (function (global) {
      var plugin = 'bootstrap'; 
      var map = {
          // our app is within the app folder
          app: 'app',
          '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
          '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
          '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
          '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
          '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
          '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
          '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
          '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
                    // other libraries
            'angular2-modal':'npm:angular2-modal',   
          'rxjs':                      'npm:rxjs',
          'angular-in-memory-web-api': 'npm:angular-in-memory-web-api',

        };
        var packages= {
          app: {
            main: './main.js',
            defaultExtension: 'js'
          },
          rxjs: {
            defaultExtension: 'js'
          },
          'angular-in-memory-web-api': {
            main: './index.js',
            defaultExtension: 'js'
          },
          'angular2-modal': {
            main: 'bundles/angular2-modal.umd',
            defaultExtension: 'js'
          }
          };
  map[`angular2-modal/plugins/${plugin}`] = map['angular2-modal'] + '/bundles';
  packages[`angular2-modal/plugins/${plugin}`] =  { defaultExtension: 'js', main: `angular2-modal.${plugin}.umd` };
      var config = {
    paths: {
          // paths serve as alias
          'npm:': 'node_modules/'
        },
    
    map: map,
    packages: packages
  };

  System.config(config);
      
    })(this);

**Comment by blahblahyaya** [comment]
I had to use: 
```
function(global) {
  var plugin = 'bootstrap'; 
  // map tells the System loader where to look for things
  var map = {
    'app':                        'dist', // 'dist',
    '@angular':                   'node_modules/@angular',
    'rxjs':                       'node_modules/rxjs',
    'ngx-modialog':               'node_modules/ngx-modialog'  
  };
  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                       { defaultExtension: 'js' },
    'ngx-modialog': { main: 'bundle/ngx-modialog', defaultExtension: 'rollup.umd.js' },
    'ngx-modialog/plugins/bootstrap': { main: 'bundle/ngx-modialog-bootstrap', defaultExtension: 'rollup.umd.js' }
  };
```
