### ISSUE TITLE
how to open a new modal, from inside a custom modal

### ISSUE THREAD

**Issue by RonenAzachi** [shlomiassaf/angular2-modal#27]
is there a way to trigger an event from with in a custom modal? 

thanks,

**Comment by NicolasCayet** [comment]
I'm would like to re-open this issue.

I'm trying to open a modal.confirm() modal into a custom modal (within a beforeClose(), returning false).
The custom modal window just disappears when it has to open it. Below is my code...

`beforeClose(): boolean {
    if (this.form && this.form.dirty && !this.submitted) {
      console.log('should open modal');

      let dialog:Promise<ModalDialogInstance> = this.modal.confirm()
        .size('sm')
        .cancelBtn(this.langService.translate('btn_cancel'))
        .okBtn(this.langService.translate('btn_ok'))
        .title(this.langService.translate('confirm_exit_modal_title'))
        .body(this.langService.translate('confirm_exit_modal_form_body'))
        .open();

      dialog.then(resultPromise => {
        return resultPromise.result.then(result => {
          console.log('back to main');
        }, () => { console.error('error') });
      });

      return false;
    } else {
      return true;
    }
  }`

Obviously, the console print "should open modal", but never "back to main" nor "error"
