### ISSUE TITLE
Can't bind to 'show-close'

### ISSUE THREAD

**Issue by holtjonathan** [shlomiassaf/angular2-modal#270]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

I followed the steps from the quick start example.  However, I am getting the following error thrown in the zone.js file:

Unhandled Promise rejection: Template parse errors:
Can't bind to 'show-close' since it isn't a known property of 'modal-header'.
1. If 'modal-header' is an Angular component and it has 'show-close' input, then verify that it is part of this module.
2. If 'modal-header' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.

Has anyone seen this issue before?

**Comment by shlomiassaf** [comment]
Does modal header has `@Input` for show-close? 


Anyway, not related to this library, it's you're own implementation since this library does not have a `modal-header` component.
