### ISSUE TITLE
Issue while trying to center Angular2-modal

### ISSUE THREAD

**Issue by vijender1256** [shlomiassaf/angular2-modal#271]
I am trying to center the angular2-modal, seems like its a issue with the control ?

plunker:

http://plnkr.co/edit/ZeRajGkGwyvKRIZkG4XQ?p=preview

Click here to see the modal is top-left aligned, I am looking to seeing it centered:

http://run.plnkr.co/Z5IUNqtFHzhyy5K4/

**Comment by shlomiassaf** [comment]
Hi

Take a look at the [demo application](http://shlomiassaf.github.io/angular2-modal/#/bootstrap-demo)

Click on the **Custom Modal Content** button, you will see it's centered.

The alignment is not set by the component but by the bootstrap CSS.

The demo app is part of this repo, follow the code and you'll find your error.

**Comment by vijender1256** [comment]
fixed the issue with custom css
