### ISSUE TITLE
Possible to call custom components in .body section?

### ISSUE THREAD

**Issue by agustincelentano** [shlomiassaf/angular2-modal#272]
Hi, it's only a question about functionality. Is possible to call custom components in the body section? 
Like this: 

this.modal.alert()
            .size('lg')
            .showClose(true)
            .title('URLS AND MD5s')
            .body(`
            
            <b>Configuration:</b>
             <div  *ngFor="let url of urls">
                <p>{{url.url }}</p>
            </div>
                
            `)
            .open();

Should be working something like this?

Thanks in advance

**Comment by shlomiassaf** [comment]
Tracked in #277

**Comment by et-taousy** [comment]
we can add selector component in body like this : 
 
this.modal.alert()
            .size('lg')
            .showClose(true)
            .title('A simple Alert style modal window')
            .body('<app-orders></app-orders>')
            .open();
i get get WARNING: sanitizing HTML stripped some content (see http://g.co/ng/security#xss).

**Comment by maximelafarie** [comment]
Mentioned this error too in #321.
