### ISSUE TITLE
escape key closes all modals

### ISSUE THREAD

**Issue by dbandstra** [shlomiassaf/angular2-modal#28]
It should only close the topmost one.

I thought of calling event.stopImmediatePropagation() in the documentKeypress method in BootstrapModalContainer, but unfortunately that causes the modals to be closed in reverse order.

I guess the only solution is to put the keydown listener on the modal itself, not the document body? Or else do a single body keydown listener and iterate the open modals somehow?

**Comment by shlomiassaf** [comment]
fixed in 0.0.6
