### ISSUE TITLE
Cannot run project locally

### ISSUE THREAD

**Issue by dagi12** [shlomiassaf/angular2-modal#287]
I try following steps to run project locally

```
git clone https://github.com/shlomiassaf/angular2-modal.git  
npm install  
typings install  
npm run start
```
This lead me to the following error
`typings WARN enoent Path "C:\aplikacje\angular2-modal\typings.json" is missing`

If I ignore that and conitnue I got this error from node on server start.
`TypeError: webpack.validateSchema is not a function`

**Comment by shlomiassaf** [comment]
you dont need typings, updated a new build, try now.

**Comment by dagi12** [comment]
Works liike a charm thanks

**Comment by xiaoanhou** [comment]
Cannot run on Windows 10, cannot install typings and cannot run:
typings install:
typings WARN enoent Path "C:\aplikacje\angular2-modal\typings.json" is missing

npm run start:
[at-loader] TS2688: Cannot find type definition file for 'hammerjs'.

[at-loader] TS2688: Cannot find type definition file for 'node'.

[at-loader] TS2688: Cannot find type definition file for 'source-map'.

[at-loader] TS2688: Cannot find type definition file for 'uglify-js'.

[at-loader] TS2688: Cannot find type definition file for 'webpack'.

[at-loader] src\demo\app\app.ts:2:1
    TS2304: Cannot find name 'require'.

[at-loader] src\demo\app\app.ts:12:5
    TS2304: Cannot find name 'require'.

[at-loader] src\demo\app\app.ts:14:13
    TS2304: Cannot find name 'require'.

[at-loader] src\demo\app\bootstrap-demo\bootstrap-demo-page\bootstrap-demo-page.ts:16:12
    TS2304: Cannot find name 'require'.

[at-loader] src\demo\app\bootstrap-demo\bootstrap-demo-page\bootstrap-demo-page.ts:17:13
    TS2304: Cannot find name 'require'.

[at-loader] src\demo\app\bootstrap-demo\modal-customisation-wizard\modal-customisation-wizard.ts:11:15
    TS2304: Cannot find name 'require'.

[at-loader] src\demo\app\demo-head\deam-head.ts:34:13
    TS2304: Cannot find name 'require'.

[at-loader] src\demo\app\home\home.ts:8:13
    TS2304: Cannot find name 'require'.

[at-loader] src\demo\app\js-native-demo\js-native-demo.ts:9:15
    TS2304: Cannot find name 'require'.

[at-loader] src\demo\app\vex-demo\vex-demo.ts:22:5
    TS2304: Cannot find name 'require'.

[at-loader] src\demo\app\vex-demo\vex-demo.ts:23:5
    TS2304: Cannot find name 'require'.

[at-loader] src\demo\app\vex-demo\vex-demo.ts:24:5
    TS2304: Cannot find name 'require'.

[at-loader] src\demo\app\vex-demo\vex-demo.ts:25:5
    TS2304: Cannot find name 'require'.

[at-loader] src\demo\app\vex-demo\vex-demo.ts:26:5
    TS2304: Cannot find name 'require'.

[at-loader] src\demo\app\vex-demo\vex-demo.ts:27:5
    TS2304: Cannot find name 'require'.

[at-loader] src\demo\app\vex-demo\vex-demo.ts:28:5
    TS2304: Cannot find name 'require'.

[at-loader] src\demo\app\vex-demo\vex-demo.ts:29:5
    TS2304: Cannot find name 'require'.

[at-loader] src\demo\app\vex-demo\vex-demo.ts:31:13
    TS2304: Cannot find name 'require'.

[at-loader] src\polyfills.ts:43:3
    TS2304: Cannot find name 'require'.
