### ISSUE TITLE
Modal align

### ISSUE THREAD

**Issue by joseSerapicos** [shlomiassaf/angular2-modal#29]
Hi, it's possible to aligner the modal at the center of the screen? When we have a scroll down and open the modal we can't see the modal so we have to scroll up every time we open the modal.
Thanks

**Comment by shlomiassaf** [comment]
Modal alignment is handled by bootstrap CSS,  do you mean it's not aligned like the original bootstrap lib?

**Comment by shlomiassaf** [comment]
This was fixed when #31 was fixed

If you need alignment see #39 and use dialogClass to change the class and set alignment's in CSS.

**Comment by joseSerapicos** [comment]
Hi, thanks for your effort, it is a very useful component and I appreciate the latest changes. I need that modal always aligned to the center of the screen and to allow scroll whenever the modal is larger than the screen (modal need to create the scrool), so I made this simple change, if someone has a better idea post here please:

- angular2-modal/src/components/angular2-modal/components/bootstrapModalContainer.ts
<pre><xmp>
<div [ngClass]="dialogInstance.config.dialogClass"
          [class.modal-lg]="dialogInstance.config.size == \'lg\'"
          [class.modal-sm]="dialogInstance.config.size == \'sm\'">
         <div class="modal-container">
             <div class="modal-content" (click)="onContainerClick($event)" style="display: block">
                 <div style="display: none" #modalDialog></div>
             </div>
        </div>
    </div>
</xmp></pre>
- css:
<pre><xmp>
.in.modal-backdrop + .in.modal {
    z-index: 2040 !important;
}
.in.modal-backdrop + .in.modal > div {
    display: table !important;
    height: 100%;
    margin: auto;
}
.in.modal-backdrop + .in.modal > div > .modal-container {
    display: table-cell !important;
    vertical-align: middle;
    background-color: transparent;
}
</xmp></pre>
![screenshot from 2016-04-01 20-16-20](https://cloud.githubusercontent.com/assets/16598702/14218107/1bd902ca-f84a-11e5-8f4a-3b4bcb026d52.png)

**Comment by shlomiassaf** [comment]
I suggest to change the `modal-dialog` to a custom class and provide a custom modal-content implementation (replace MessageModal) with your own angular 2 component.

Make the size adjustment and set the container to fixed so no scrolling is allowed.

The current customisation options should allow to do that.

**Comment by joseSerapicos** [comment]
Yes, I can do this, thanks for the suggestion :)
