### ISSUE TITLE
Usage with SystemJS

### ISSUE THREAD

**Issue by mugdho** [shlomiassaf/angular2-modal#30]
Hi,
I added the modal using npm and added it to my SystemJS bindings as below. But the angular2 polyfill doesn't seem to be capable to load it. Is there something I am doing incorrectly in the mapping below? Since I didnt find any examples with SystemJS in the demo code I wasnt sure if there was full SystemJS support yet. Sorry I am a noob to both Ng2 and SystemJS, so I may be missing something completely fundamental.

```
map: {
                    'angular2-modal': "node_modules/angular2-modal/dist/angular2-modal"
                }
```

**Comment by shlomiassaf** [comment]
System JS bundle was added, please see http://plnkr.co/edit/FnGdwU

**Comment by squarewave24** [comment]
I have the same problem. 
appears the problem is that they want to reference 2 files in different directions 

    node_modules/bundles/angular2-modal.umd.js
    node_modules/plugins/bootstrp/bootstrap.module.js

having a really hard time configuring systemjs.config for this :/

**Comment by mail19** [comment]
on the bottom of the page: 
Sample code: Custom Modal dialog

http://embed.plnkr.co/mbPzd8/

http://embed.plnkr.co/ZAZqZu/ (version 1.1.1)

Click the first link and you'll see the systemjs.config.js. I followed the way it is set up and modal started working
