### ISSUE TITLE
Adding custom buttons in bootstrap Confirm dialog

### ISSUE THREAD

**Issue by bvaissade** [shlomiassaf/angular2-modal#310]
Like in my previous issue #285, i want to change buttons positions in confirm dialog.

I try 

```
showBoxOuiNonRds(titre: string, msg: string): Promise<DialogRef<TwoButtonPreset>> {
    return this.modal.confirm()
      .size('lg')
      .isBlocking(true)
      .showClose(true)
      .keyboard(27)
      .title(titre)
      .body(msg)
      .cancelBtn(null)
      .okBtn(null)
      .addButton('btn btn-default', 'Cancel', this.closeModalCancel)
      .addButton('btn btn-primary', 'Ok', this.closeModalCancel)
      .open();
  }
```

in my service. 

I can see my news buttons but allsaw smalls one !
And how i define my BSMessageModalButtonHandler.

Thanks by advance.

**Comment by baldassarreFe** [comment]
Not the best way to go, but meanwhile you could use:
.okBtnClass("hidden")
.cancelBtnClass("hidden")

The okBtn(null) and cancelBtn(null) methods simply set the text inside the buttons. Adding the "hidden" class will hide the buttons from the view, even though they will be present in the DOM (check with the inspector).

**Comment by bvaissade** [comment]
Thanks !
It's work. But now how do I Handle click on my mew buttons to validate or dismiss dialog ?

**Comment by byronsliger** [comment]
The onClick of addButton return a dialog footer, so 
You should add the next code on closeModalCancel add
```
  closeModalCancel(dialogFooter) {
    dialogFooter.dialog.dismiss();
  }
```
to dismiss dialog. this call `.catch((err: any) => { console.log("erro") });` promise

and add
```
closeModalOk(dialogFooter){
    dialogFooter.dialog.close();
}
```
on closeModalOk for ok result, and this call ok promise
```
.then((dialog: any) => { return dialog.result })
.then((result: any) => { this.action() })
```
I hope this can help you.

**Comment by bvaissade** [comment]
It's ok ! Thanks a lot.

**Comment by rrohitesh** [comment]
How Can we capture then return of this on the button press

```
 onWarning(title: String, message: String) {
  return this.modal.alert()
            .size('sm')
            .showClose(false)
            .isBlocking(true)
            .okBtn(null)
            .okBtnClass('hide-ok')
            .addButton('btn btn-default', 'Accept', function (dialogFooter) {
                console.log('ok calback');
                dialogFooter.dialog.dismiss();
                response = true;
                return false;
            })
            .addButton('btn btn-default', 'Discard', function (dialogFooter) {
                console.log('cancle calback');
                dialogFooter.dialog.dismiss();
                response = false;
                return true;
            })
            .body(`
                <div class="modal-body">
                <div class="header-image">     
            <i class="fa fa-exclamation-triangle fa-lg" aria-hidden="true" ></i>
                </div>
                    <h1>` + title + `</h1>
                    <div class="modal-message">` + message + `</div></div>`)
            .open().then(result => {
                console.log('result', result);

            });
}
```

I want this function to return true or false based on the ACCEPT or DISCARD callback button pressed.

**Comment by rmcsharry** [comment]
If you modify the demo plunker to shorten the title you can see this problem also.

![image](https://user-images.githubusercontent.com/1156100/32247741-993698ee-be83-11e7-9836-665cad484d81.png)

**Comment by danielheth** [comment]
This is how i solved the switching of the ok/cancel buttons.  I have no need for the dialog result... only need to know if the user pushed ok or cancel...
```
const dialogRef = this.modal
      .confirm()
      .size('lg')
      .showClose(false)
      .title('Dialog Title')
      .body('<p>Are you sure?</p>')
      .okBtn('Cancel')
      .okBtnClass('btn btn-default')
      .cancelBtn('OK')
      .cancelBtnClass('btn btn-primary')
      .open();

    dialogRef.result
      .then(() => {
        console.log('Cancel Clicked');
      })
      .catch(()=> {
        console.log('OK Clicked');
      });
```
