### ISSUE TITLE
Custom modal not targeting overlaytarget

### ISSUE THREAD

**Issue by haakotsm** [shlomiassaf/angular2-modal#317]
I can't seem to figure out how to target my overlaytarget. I've been following #166 and on paper it looks like the solution that is supposed to work.

This is how the relevant part of the method looks.
 ```
const builder = new BSModalContextBuilder<CustomModalContext>(
      { list: students } as any,
      undefined,
      CustomModalContext
    );
    let overlayConfig: OverlayConfig = {
      viewContainer: 'my-target',
      context: builder.inElement( true ).toJSON()
    };
    this.modal.open( CustomModalComponent, overlayConfig );
```

Part of the html
```
<div *ngIf="isLoading" class="bm-loader"><img src="../../../../assets/animal.gif"></div>
  <div *ngIf="!isLoading" class="p-2" overlayTarget="my-target" >
    <form [formGroup]="myForm" (ngSubmit)="save()">
      <div class="row m-0">
        <md-input-container class="col-5">
          <input type="text" mdInput placeholder="Gruppenavn" formControlName="name">
        </md-input-container>
      </div>
      <div class="row m-0">
```
Even with this it keeps on targeting the defaultoverlaytarget in my app root.

Console logged the output of the overlay and the modal
![image](https://cloud.githubusercontent.com/assets/8438820/23895440/04c02600-08a6-11e7-9190-752d4391f5a2.png)
-

I've dug deep through your source code and tried a lot of different things, but to no avail. It should be displayed inside the panel in the background and not the whole page.

![image](https://cloud.githubusercontent.com/assets/8438820/23895598/98e5d38e-08a6-11e7-8729-9622a5cd3750.png)

I'm using this in combination with BTMortons Angular2-Grid if that makes any difference.
https://github.com/BTMorton/angular2-grid

* **Please tell us about your environment:**

- Angular version: 2.4.0
- Browser: [all]

**Comment by narendra-agashe** [comment]
any luck @haakotsm ?
I am working on same functionality and running into same problem.

**Comment by haakotsm** [comment]
We ended up moving  the application in another direction. Discontinued the panels. Also we were using bootstrap 4, which was part of the problem guessing from other issues on this git. If you'rẻ using bootstrap 4, I'd suggest trying with the ng-bootstrap library.
