### ISSUE TITLE
Cleaner API for content

### ISSUE THREAD

**Issue by AbdulRahmanAlHamali** [shlomiassaf/angular2-modal#33]
Hello,

Thank you for this modal, it is very neat!

I just think it is kind of too dirty to have to get a Injector and provide and useValue and all of this when all I want is to provide the modal with its content, would it be possible to provide easier API for that where we just provide the content?

Thank you!

**Comment by AbdulRahmanAlHamali** [comment]
Actaully I'm sorry for that the library really seems so nice, but it takes so much just to call a YesNo dialog box. There is even a promise inside a promise.

**Comment by shlomiassaf** [comment]
You're right, I'll add helpers.

**Comment by shlomiassaf** [comment]
This is the planned API

```
this.modal.alert()
            .modalConfig(new ModalConfig('sm', false, 27))
            .title('Hello')
            .content('World')
            .ok('EXIT')
            .open()
            .then((mdi: ModalDialogInstance) => {
                mdi.result.then(() => alert('ok'));
            });
```
> Note: not finel.

I plan to support some other scenarios.

It's quite similar to the API used in the dialog service in Angular Material Design.
