### ISSUE TITLE
Custom modal in a lazy-loaded module (Webpack)

### ISSUE THREAD

**Issue by pilgylis** [shlomiassaf/angular2-modal#331]
Fork URL: https://github.com/pilgylis/angular2-webpack-starter/tree/master

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
I have a custom dialog in a lazy-loaded module. When trying to show it, an error "No component factory found for TestDialog1Component. Did you add it to @NgModule.entryComponents?" was encountered.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use one of the templates above as a starting point).
Fork URL: https://github.com/pilgylis/angular2-webpack-starter/tree/master

Please try to access http://localhost:3000/#/detail and click on the button **"Show Dialog"**.

* **What is the expected behavior?**
The dialog is opened without error

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.4.6
- Browser: [all]
- Webpack 2.3.1

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by AlexViderman** [comment]
I use lazy loaded modules with a custom dialog successfully. Here is an example, I have a Users Module with an Edit User custom dialog. Here is what my module looks like. Make sure you add the declaration to the "entryComponents", I have it in bold below:

import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { SecureUsersComponent }   from './secure.users.component';
import { SharedGlobalModule} from '../../shared/modules/shared.global.module'
**import { EditUserWindow } from './secure.users.edit.component';**

const routes: Routes = [
  { path: '', component: SecureUsersComponent },
];

@NgModule({
  imports: [
    RouterModule.forChild(routes),
    SharedGlobalModule
  ],
  exports: [],
  **declarations: [SecureUsersComponent,EditUserWindow],**
  providers: [],
  **entryComponents: [EditUserWindow]**
})
export class SecureUsersModule { }

...

Where EditUserWindow is the custom modal:

...
export class EditUserWindow implements ModalComponent<EditUserData> {
....

**Comment by valentinpascau** [comment]
@AlexViderman  thx for sharing this, I think the problem is how the `ModalModule` is imported since the 
 custom dialog from the above fork is added to `entryComponents`. In my case i was able to make it working by importing `ModalModule.forRoot()` in  the lazy loaded module; also the `<span defaultOverlayTarget></span>` was "not working" in the application root component template , but in the lazy loaded module template. I suppose that you are importing the `ModalModule` in `SharedGlobalModule`?; can you please tell if you are doing it in the same way(in `SharedGlobalModule` or in app root module)? also where is the `<span defaultOverlayTarget></span>` located in your app?

**Comment by AlexViderman** [comment]
@valentinpascau , yeah I am importing ModalModule.forRoot() in my SharedGlobalModule and exporting ModalModule. I've been manually setting the defaultViewContainer in every component where I need to use the modal:

import { Component, OnInit, ViewContainerRef } from '@angular/core';
import { Overlay } from 'angular2-modal';

export class SecureUsersComponent implements OnInit {

constructor(overlay: Overlay, vcRef: ViewContainerRef) {
    overlay.defaultViewContainer = vcRef;
 }
}

I tried to get <span defaultOverlayTarget> working, but got stuck, I will mess around with it some more and see if I can figure out how to get that directive working at the app component level, and not the lazy loaded component. Will post an update if I figure it out!

**Comment by pilgylis** [comment]
Thanks @AlexViderman, although it looks strange to me when you have to set defaultViewContainer in every component.

**Comment by AlexViderman** [comment]
@pilgylis all of my components that use modals are lazy loaded, I have not invested too much time trying to avoid manually setting it... i am a little hesitant to invest more into this module since its not being maintained and I may have to switch to ngx-bootstrap or ng-bootstrap soon. ng-bootstrap seems to have a very easy custom modal implementation: https://ng-bootstrap.github.io/#/components/modal ("Components as content")

**Comment by pilgylis** [comment]
The cause to this is, the scopes of lazy loaded modules are different than the root scope, so Overlay is recreated.

My solution is to override the registration of ModalModule.forRoot() and use a different factory for Overlay:


        // ModalModule.forRoot(),
        {
          ngModule: ModalModule,
          providers: [
            {
                provide: Overlay,
                useFactory: (renderer: OverlayRenderer) => {
                  console.log("Overlay requesting");
                  let mWindow = <any>window;
                  if (!mWindow.overlay) {
                    mWindow.overlay = new Overlay(renderer);
                  }
                  return mWindow.overlay;
                },
                deps: [OverlayRenderer]
            },
            {provide: OverlayRenderer, useClass: DOMOverlayRenderer},
            {provide: EVENT_MANAGER_PLUGINS, useClass: DOMOutsideEventPlugin, multi: true},
            // {provide: ANALYZE_FOR_ENTRY_COMPONENTS, useValue: [], multi: true}
          ]
        },

**Comment by pilgylis** [comment]
Sorry that my last post did not work.

I managed to get this to work by override the Overlay service and remove its dependence on defaultViewContainer. I use ApplicationRef to attach the view instead of using defaultViewContainer.

**Comment by shlomiassaf** [comment]
Hi guys, please try version 3.0.1

Update if it works and it not :)

**Comment by AlexViderman** [comment]
@shlomiassaf, thank you for the update, the template errors are gone and not having to specify defaultViewContainer made things easier. Everything else seems to be working like before.

**Comment by pilgylis** [comment]
Awesome!
