### ISSUE TITLE
AOT compilation error using angular2-modal 2.0.2

### ISSUE THREAD

**Issue by aleksclark** [shlomiassaf/angular2-modal#335]
`ERROR in Error encountered resolving symbol values statically. Expression form not supported (position 89:30 in the original .ts file), resolving symbol OverlayContextBuilder in ..app/node_modules/angular2-modal/esm/models/overlay-context.d.ts`

* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

Report a bug.

* **What is the current behavior?**

AOT compilation with `ng build --aot` fails with the above error

* **What is the expected behavior?**

Successful AOT compilation

* **What is the motivation / use case for changing the behavior?**

I want a functional AOT build of my app.

* **Please tell us about your environment:**

- Angular version: 4.0.0
- angular/cli version: 1.0.0
- Browser: all

**Comment by lewisames** [comment]
I was having the same problem yesterday.  I just uninstalled the module, and reinstalled the 2.0.3 version and that error has gone away

**Comment by aleksclark** [comment]
this fixed it, thanks!
