### ISSUE TITLE
Use <ng-template> instead of the deprecated <template>

### ISSUE THREAD

**Issue by Daedalon** [shlomiassaf/angular2-modal#338]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**

1. Create a project with NG CLI 1.0 (uses Angular 4.0)
2. Include angular2-modal the same way as before
3. Run `ng build --prod`
4. The following notice is displayed:

> Template parse warnings:
> The <template> element is deprecated. Use <ng-template> instead ("[WARNING ->]<template #innerView></template>
> <template #template let-ctx>
>     <template [swapCmp]="ctx.component"")

The deprecated `<template>` tag is used in angular2-modal\bundles\angular2-modal.umd.js line 1228 and angular2-modal\bundles\angular2-modal.vex.umd.js line 71, among a number of other files.

**Comment by bartholomej** [comment]
Duplicate #312

**Comment by mspriggs** [comment]
+1

**Comment by WillooWisp** [comment]
Yes please update to support angular v 4.

**Comment by achimha** [comment]
Now is probably the time to do the move, a lot of major packages have done it.

**Comment by davidanaya** [comment]
+1

**Comment by sreedharbukya** [comment]
+1

**Comment by hosiduy** [comment]
+1

**Comment by ltorresortiz** [comment]
+1

**Comment by stevie6410** [comment]
+1

**Comment by shlomiassaf** [comment]
fixed in 3.0.0

**Comment by FirassKoubaa** [comment]
+1
