### ISSUE TITLE
Need some help mocking dialogRef so that I can test the then path.

### ISSUE THREAD

**Issue by mardon1975** [shlomiassaf/angular2-modal#339]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
**[*] question about testing, and mocking**

As of now I can mock out the modal.open, but currently I am fighting, and struggling with trying to mock the dialogRef. Has anybody tried to mock out the results of the dialogRef so that I can test out any of my methods that use the result.then. Any example of how I can go about mocking this out to finish the unit testing would be greatly appreciated. You can see an example of the code that I am trying to test below.

            this.modal.open(ConfirmationModalComponent,
                overlayConfigFactory(<ConfirmationModalContext>{
                        title: this.translateService.instant("LoadNewSession"),
                        body: this.translateService.instant("LoadNewSessionBody"),
                        okButtonText: this.translateService.instant("Yes"),
                        cancelButtonText: this.translateService.instant("No")
                    },
                    ConfirmationModalContext)).then(dialogRef => { dialogRef.result.then(
                    () => {
                        this.fileSelector.nativeElement.value = null;
                        this.fileSelector.nativeElement.click();
                    },
                    () => { });
            }).catch(error => {
                this.messageService.displayMessage(MessageTypes.Error, error.message);
            });

Update: Currently I can mock and test most standard modals, plus I can at least cause the error condition to fire. What i am struggling with is I can't currently mock out the dialogRef and have it return like the code I am trying to is returning.

**Comment by mardon1975** [comment]
Closing this issue.

**Comment by samudurand** [comment]
@mardon1975  Did you find any solution ?
