### ISSUE TITLE
Warning when installing with angular 4

### ISSUE THREAD

**Issue by tobmaster** [shlomiassaf/angular2-modal#357]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
"bug"

* **What is the current behavior?**
During install you get a warning when using with angular 4.x
`
warning "angular2-modal@2.0.3" has incorrect peer dependency "@angular/core@^2.1.1".
warning "angular2-modal@2.0.3" has incorrect peer dependency "@angular/common@^2.1.1".
`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via

yarn add

* **What is the expected behavior?**
No warning

* **What is the motivation / use case for changing the behavior?**
To prevent warning noise the package should state its angular 4 compatibility

* **Please tell us about your environment:**

- Angular version: 4.1.2

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Pull request https://github.com/shlomiassaf/angular2-modal/pull/356

**Comment by EduardoIbarra** [comment]
For me, it is completely f*d up, it doesn't allow me to show a simple select or display a table well. I am using Angular 4 as well.

**Comment by shlomiassaf** [comment]
Fixed in 3.0.0
