### ISSUE TITLE
Allow adding custom classes on modal-dialog

### ISSUE THREAD

**Issue by ellern** [shlomiassaf/angular2-modal#36]
This would allow custom styling and positioning of modals.

The custom classes could be enabled through the `ModalConfig` with `classes: string` property and by adding `[ngClass]="dialogInstance.config.classes || ''"` to the `BootstrapModalContainer` template.

This would make modal alignment as mentioned in #29 easy to do with a little css.

**Comment by ellern** [comment]
How do I set a custom class on the modal-dialog element?

**Comment by shlomiassaf** [comment]
It should look like this
```
modal.alert()
    .headerClass('modal-header')
    .title('Hello World')
    .body('A Customized Modal')
    .bodyClass('modal-body')
    .footerClass('modal-footer')
    .okBtnClass('btn')
    .open();
```

Play with the generator to see other options... http://shlomiassaf.github.io/angular2-modal#/customizeModals

**Comment by shlomiassaf** [comment]
Basically there is a 1 custom modal that I'v implemented that replace the old ones (okOnly, yesNo)

I've built the alert,prompt and confirm presets around it which provides a lot of flexibility.

If a more advanced scenario is needed a custom modal is needed...

**Comment by ellern** [comment]
I'm aware of the headerClass, bodyClass and footerClass, but that will not allow you to do any positioning. That why I wanted to see a way to add a class to the modal-dialog. It could be an optional `.modalClass('my-custom-modal')´ in the fluent api

**Comment by shlomiassaf** [comment]
The problem with modal-dialog is that it hold the "size" css class.
So, What would you think is the best approach here?

Template:
```
    `<div class="modal-dialog"
         [class.modal-lg]="dialogInstance.config.size == \'lg\'"
         [class.modal-sm]="dialogInstance.config.size == \'sm\'">
         <div class="modal-content" (click)="onContainerClick($event)" style="display: block">
            <div style="display: none" #modalDialog></div>
         </div>
    </div>`
```

So having a custom css class should override the size, which then creates a weird behaviour...

**Comment by ellern** [comment]
Doing something like this will not override the size class

    <div class="modal-dialog"
         [ngClass]="dialogInstance.config.modalDialogClass || ''"
         [class.modal-lg]="dialogInstance.config.size == \'lg\'"
         [class.modal-sm]="dialogInstance.config.size == \'sm\'">
         <div class="modal-content" (click)="onContainerClick($event)" style="display: block">
            <div style="display: none" #modalDialog></div>
         </div>
    </div>

**Comment by shlomiassaf** [comment]
Yep I agrre but that doesn't solve my issue.
`config.size` has a default value, usually "lg".
So a user will have to do
```
modal.alert()
    .size('')
    .modalDialogClass('something')
    .open()
```

To get the class to be what he wanted...

Maybe setting modalDialogClass will also override size?

**Comment by shlomiassaf** [comment]
You know what, overriding make's sense, if someone wants to be explicit then by all means, all the way.

**Comment by ellern** [comment]
There should be room for both - I my current setup I use both `lg` and custom class

**Comment by shlomiassaf** [comment]
If u'r setting a custom modal-dialog class you will need to set "modal-lg" as a custom class.
e.g: `modal.alert().dialogClass('my-cutom modal-lg')`

I think it looks better then `modal.alert().dialogClass('my-cutom').size('')`

**Comment by shlomiassaf** [comment]
> Btw. don't know if modalDialogClass would be the best fit for a name. What about modalClass to keep it aligned with the headerClass

The naming convention is xClass where x is the original class name without the modal (modal-x).
e.g: modal-header -> headerClass 

So it will be dialogClass

**Comment by ellern** [comment]
Makes sense

**Comment by shlomiassaf** [comment]
BTW, you know that all xClass methods **override** the class, so setting `dialogClass` will remove the original class (modal-dialog), if it's addition you're after you will have to do `modal-dialog my-css`

There's no other option...

**Comment by ellern** [comment]
I'm not seeing that behaviour using beta12.

When I'm using `[ngClass]="dialogInstance.config.modalDialogClass || ''"` I get the value from the config added to the class list. My modal-dialog ends of with the following class list: `modal-dialog lg custom`

**Comment by shlomiassaf** [comment]
I talked about general behaviour of xClass in the preset's.

As for the expression `dialogInstance.config.modalDialogClass` it invalid because `dialogInstance.config` is not the preset API, it's an instance of `ModalConfig` which is build from the preset, but it's not the preset so `dialogInstance.config.modalDialogClass` will always be null.

The actual preset is injected into the Modal component itself.

The preset is wrapper that combine's the two, but when doing a manual implementation they are separate.

**Comment by ellern** [comment]
Okay, I misunderstood. Btw. the `dialogInstance.config.modalDialogClass` is just something I have in a local fork - switching to your new fluent api version when the dialogClass is implemented.

**Comment by shlomiassaf** [comment]
Cool :+1: 

It will probably end up (dialogClass) on the config object since it's a level above the modal component...

**Comment by shlomiassaf** [comment]
See latest commits, modal-dialog is enabled via `dialogClass `

You can verify it in the code generator.

If `size` is set it will not remove it, I left it as you requested originally

npm version 0.1.1
