### ISSUE TITLE
How to redirect after clicking "OK" button?

### ISSUE THREAD

**Issue by jdushi** [shlomiassaf/angular2-modal#361]
this.modal.alert()
                  .size('lg')
                  .showClose(true)
                  .title('A simple Alert style modal window')
                  .body(`Alert is a classic (title/body/footer) 1 button modal window that does not block.`)
                  .okBtnClass('btn btn-default')
                  .open()
.then(function () {
                    this.router.navigate(['welcome']);
                  }.bind(this));

I tried with a promise but the modal is not shown

**Comment by qwe852147** [comment]
body will be string and you can reference #352 to do calling  function

**Comment by jdushi** [comment]
@qwe852147 I did not found a solution, so I used another modal component. Thank you for your response. It might be useful to others.
