### ISSUE TITLE
Error: No component factory found for BSModalContainer

### ISSUE THREAD

**Issue by kadosh1000** [shlomiassaf/angular2-modal#365]
When opening a custom modal using the following code: 
`this.modal.open(ModalComponent, overlayConfigFactory({},BSModalContext))`

I get the following error:

> Error: No component factory found for BSModalContainer. Did you add it to @NgModule.entryComponents?

The modal indeed opens and displayed well, but I would like to get rid of that error message.

Have anyone encountered that error before?

**Comment by shlomiassaf** [comment]
Version?

**Comment by kadosh1000** [comment]
@shlomiassaf  sorry forgot to mention.
I am using angular 4.0.2 and angula2-modal 3.0.0

**Comment by shlomiassaf** [comment]
Lazy loading by chance ?

**Comment by kadosh1000** [comment]
Nope :(

**Comment by kadosh1000** [comment]
found what the problem was. I didn't notice I need to import the `BootstrapModalModule`.
After importing it the error went away
