### ISSUE TITLE
Error: BootstrapModalContainer'(ModalDialogInstance, undefined). 

### ISSUE THREAD

**Issue by lanocturne** [shlomiassaf/angular2-modal#40]
👋, getting below error when trying to open a custom modal.
```
EXCEPTION: Cannot resolve all parameters for 'BootstrapModalContainer'(ModalDialogInstance, undefined). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'BootstrapModalContainer' is decorated with Injectable.
```

Here is a snippet of the modal code
```ts
import {ICustomModalComponent, ICustomModal} from "angular2-modal/dist/commonjs/models/ICustomModal";
import {ModalDialogInstance} from "angular2-modal/dist/commonjs/models/ModalDialogInstance";

export class PreviewModal implements ICustomModalComponent {
  dialog: ModalDialogInstance;
  context: PreviewModalData;

  constructor(dialog: ModalDialogInstance, modelContentData: ICustomModal) {
    this.dialog = dialog;
    this.context = <PreviewModalData>modelContentData;
    console.log(this.context);
  }
...
```

ng2 version:  beta.9
bundler: webpack

**Comment by shlomiassaf** [comment]
The constructor has 2 parameters injected into it
the dialog parameter is known.
the modelContentData is not, you need to `provide` a value for the ICustomModal token in order to get data into the component.

Or, you can just remove it if you dont need it (or put @Optional if its so)

**Comment by lanocturne** [comment]
Still getting this error after remove second parameter or add @Optional.

I think something is wrong on parent component. Here is the code:
```ts
import {Component, Injector, provide, Input} from "angular2/core";
import {ICustomModal} from "angular2-modal/dist/commonjs/models/ICustomModal";
import {Modal} from "angular2-modal/dist/commonjs/providers/Modal";
import {ModalConfig} from "angular2-modal/dist/commonjs/models/ModalConfig";
import {ModalDialogInstance} from "angular2-modal/dist/commonjs/models/ModalDialogInstance";
...
providers: [Modal]
})

constructor(public modal: Modal) {
  }
openModal() {
    let resolveBindings = Injector.resolve([provide(ICustomModal, {
          useValue: new PreviewModalData(this.program.Id, "NEW")
        })]), 
        dialog          = this.modal.open(<any>PreviewModal, resolveBindings, new ModalConfig("lg", true, 27));
    this.processDialog(dialog);
  }

**Comment by lanocturne** [comment]
It turns out to be my IDE's auto import issue.

Change import {Modal} from "angular2-modal/dist/commonjs/providers/Modal"; ...
from full path to 'angular2-modal', then the run time error is solved.

**Comment by dbandstra** [comment]
I just spent a couple hours with this same issue. Changing my code to import Modal from the 'angular2-modal/angular2-modal' bulk-export file instead of from the Modal file itself fixed it. I don't understand at all why this would make any difference. (So thanks Ianocturne, I would never have thought to try this!)
