### ISSUE TITLE
Pass data to custom modal

### ISSUE THREAD

**Issue by a-pavlov-parc** [shlomiassaf/angular2-modal#41]
Hi. What is the best way to pass some data to custom modal window? For example I want to pass some text and show it in textarea on the window. I don't see it on README. Thanks

**Comment by RonenAzachi** [comment]
see example of custom models

https://github.com/shlomiassaf/angular2-modal/blob/master/src/demo/app/customModalDemo/customModal.ts

see AdditionCalculateWindowData in the file.

**Comment by a-pavlov-parc** [comment]
Thanks for short answer. It's really enough

**Comment by steady-daddy** [comment]
Link is broken. File removed.

**Comment by kevintanhongann** [comment]
I don't see that.
