### ISSUE TITLE
Modal isn't popped if parent component is destroyed

### ISSUE THREAD

**Issue by dbandstra** [shlomiassaf/angular2-modal#43]
This matters to me because I actually do want (despite your TODO comment) the modal-open class to be added to the body even for modals opened inside other elements. So for me the modal-open class was getting stuck on as soon as I navigated away from a component with an open modal.

I worked around this by overriding ngOnDestroy in BootstrapModalContainer, ensuring that the dialog instance is removed from the stack. So in most cases it's actually being 'removed' twice, but that's ok. I think this makes more sense than rejecting the dialog instance's promise (the dialog instance and its promise should be considered garbage by this point), but I don't know if it's the best solution.

**Comment by shlomiassaf** [comment]
Integration with the `body` element is a temporary addition to fix the scrolling issue.

The way Angular 2 handles UI elements create's edge cases where a trivial angular 1 or jQuery task is now more tricky. 

In our case the `body` element **might** or **might not** be part of the Angular 2 runtime so accessing it might be impossible using angular runtime tools. 

The way the modal window is structured in bootstrap is tricky for angular 2 and a solution will need some thinking, I will try to make time for that.

Your solution is specific to a bigger problem, how to structure the overlay and it's interaction.

So for now, I will not find a solution for this until a more generic solution for the overlay.
