### ISSUE TITLE
DOM is null

### ISSUE THREAD

**Issue by dbandstra** [shlomiassaf/angular2-modal#44]
I don't think the code adding the 'modal-open' class to the body actually works, because DOM is apparently always null due to a bug in angular2.

For my own needs I just changed the code to modify window.document.body directly.

Using angular2 beta 12.

References:
- http://stackoverflow.com/questions/34686856/angular-2-0-beta-access-dom-adapter-browserdomadapter
- http://stackoverflow.com/questions/35799022/angular-2-dom-adapter
- https://github.com/angular/angular/issues/6904

**Comment by shlomiassaf** [comment]
Strange, you can look at the demo, or even batter at the code generator and you will see it works there.

I'm not happy with the DOM adapter direct use, it's a temp workaround to support adding a class to the body.

**Comment by shlomiassaf** [comment]
BTW, if you want DOM to be the current DOM adapter 
call `BrowserDomAdapter.makeCurrent();` before bootstrapping, this is the right way.

**Comment by dbandstra** [comment]
I don't know what's going on. That doesn't work for me. DOM imported from angular2/src/platform/dom/dom_adapter is always null, even though the makeCurrent function is running. It must be something to do with module resolution in my project. Although it seems odd to me that you would be able to reassign an exported reference (the DOM global) at all. (Disclaimer: I'm new to this stuff.)

This code, right above the bootstrap call, prints 'DOM: null'.

```typescript
BrowserDomAdapter.makeCurrent();
import {DOM} from 'angular2/src/platform/dom/dom_adapter';
console.log('DOM:', DOM);
```

The best I can do seems to be to instantiate my own BrowserDomAdapter and use it instead of this DOM global.
