### ISSUE TITLE
Dialog doesn't open after update to Angular 6

### ISSUE THREAD

**Issue by Alados** [shlomiassaf/angular2-modal#441]
IMPORTANT: Please provide a sample using: http://plnkr.co/edit/lV7zsw7Yqossgs9JOfQU?p=preview

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

Bug

* **What is the current behavior?**

Dialog exist in html, but it is invisible for user. It started to happen after updating Angular to 6 version.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use one of the templates above as a starting point).

* **What is the expected behavior?**

Dialog should open

* **What is the motivation / use case for changing the behavior?**

It started to happen after updating Angular to 6 version.

* **Please tell us about your environment:**

- Angular version:  Angular 6
- Browser: [ Chrome ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by bklep246** [comment]
I had the same issue and found that it's being defaulted to bootstrap 4 now.  The classes are different from 3 to 4 and it's causing the modal to have an opacity: 0.  To fix this you have to set it to use bootstrap 3 like this:
```
import { bootstrap3Mode } from 'ngx-modialog/plugins/bootstrap';
```

and execute in your constructor

```
  constructor(private modal: Modal) {
    bootstrap3Mode();
  }
```
https://github.com/shlomiassaf/ngx-modialog/blob/master/projects/plugins/bootstrap/src/lib/modal.ts

**Comment by greg73** [comment]
Are you using Bootstrap 3? If so you need to call bootstrap3Mode()

**Comment by Alados** [comment]
Problem was with our styles, issue might be close
