### ISSUE TITLE
Incompatible with Beta 13

### ISSUE THREAD

**Issue by chrille112** [shlomiassaf/angular2-modal#45]
Beta 13 is running rxjs@5.0.0-beta.4, but modal want rxjs@5.0.0-beta.2
Would it be possible to upgrade this dependency?

**Comment by shlomiassaf** [comment]
Angular 2 beta 13 is still on rxjs beta 2
https://github.com/angular/angular/blob/master/package.json#L37

I don't have a dependency on rxjs, angular 2 has it.

**Comment by chrille112** [comment]
Sorry, you are right! I'm closing this.
