### ISSUE TITLE
Pass callback for Ok button

### ISSUE THREAD

**Issue by guzmo** [shlomiassaf/angular2-modal#46]
Is it possible to pass a callback somehow?

```
this.modal.confirm()
            .size('sm')
            .isBlocking(true)
            .keyboard(27)
            .title('Create application')
            .body(`<label>Name</label>
                       <input class="form-control" type="text" #answer autofocus>`
             )
            .okBtn('Save')

            // Something like this....
            .onOkClicked(function() {
                   // Get value and reject or close...
            })
            .cancelBtn('Cancel')
            .open();
```

**Comment by shlomiassaf** [comment]
Why would you want to pass a callback? You have a promise.

```
this.modal.confirm()
            .title('Create application')
            .body(`<label>Name</label>
                       <input class="form-control" type="text" #answer autofocus>`
             )
            .okBtn('Save')
            .cancelBtn('Cancel')
            .open()
            .catch(err => alert("ERROR")) // catch error not related to the result (modal open...)
            .then(dialog => dialog.result) // dialog has more properties,lets just return the promise for a result. 
            .then(result => alert("SAVED")) // if were here ok was clicked.
            .catch(err => alert("CANCELED")) // if were here it was cancelled (click or non block click)
```

**Comment by shlomiassaf** [comment]
You won't find a lot of places to use callback's in angular 2 and infect in most modern frameworks... If you're using a callback your'e probably do something wrong.

**Comment by guzmo** [comment]
That works fine, didn't find what it returned in the documentation :O thanks for the quick response!

**Comment by rahulbussa** [comment]
@shlomiassaf 
How do we get values of form inputs in modal body.can you help me .

**Comment by jezguitarist30** [comment]
Hi, I'm using your example above
  this.modal.confirm()
            .title('Create application')
            .body(`<label>Name</label>
                       <input class="form-control" type="text" #answer autofocus>`
             )
            .okBtn('Save')
            .cancelBtn('Cancel')
            .open()
            .catch(err => alert("ERROR")) // catch error not related to the result (modal open...)            
            .then(result => alert("SAVED")) // if were here ok was clicked.
            .catch(err => alert("CANCELED")) // if were here it was cancelled (click or non block click)

But why do I get the Promise right after I call the Open method even though I haven't clicked on the OK or even before the Modal shows up?

**Comment by tomsvogel** [comment]
@jezguitarist30  i had the same problem. Important is to return the dialog.result first.
```
.then(dialog => dialog.result)
.then(result => alert(result))
```

**Comment by JurajKavka** [comment]
for me, typescript won't compile this ... please can You help me with this error? Thank You.

`    Property 'result' does not exist on type 'void | DialogRef<TwoButtonPreset>'.                                                       │
  Property 'result' does not exist on type 'void'.                                                                                      │npm ERR! Please include the following file with any support request:
[default] Checking finished with 1 errors`

**Comment by Brdjx** [comment]
Was looking for @tomsvogel's answer too. It works, but @JurajKavka's error is thrown for me too.

**Comment by vonbrana** [comment]
This worked for me:

 .then((dialog : any ) => dialog.result)

**Comment by JurajKavka** [comment]
Thanks @vonbrana for suggestion. My working solution was

```
 .then(dialog => { if(dialog) { return dialog.result }})
```

but Yours is much better i think. This is my working code:


```
    this._modal.confirm()
        .size('sm')
        .showClose(true)
        .title('Some title!')
        .body(_dialogText) 
        .okBtn('Yes)
        .cancelBtn('No')
        .open()
        .catch((err: any) => console.log('ERROR: ' + err))
        .then((dialog: any) => { return dialog.result })
        .then((result: any) => { this.deleteEvent() })
        .catch((err: any) => this._cleanup());
  }
```

I also tied to eliminate `any` with  `DialogRef` type but without success.

```
$ npm run tsc -v
4.1.2
```

Its all about cheating typescript :)

**Comment by secabhi** [comment]
Hi 
I am written like this

this.modal.confirm()
            .size('sm')
            .title('TADA')
            .dialogClass('modal-dialog modal-custom modal-interested')
            .headerClass('modal-header')
            .body(`${bodydata}`)
            .showClose(true)
            .okBtn('Navigate')
            .cancelBtn('Cancel')
            .open()
            .then((result: any) => { window.open('www.google.com','_blank') })

But its redirecting me before click on navigate button . Please help me this . I want to navigate on Button click

**Comment by JurajKavka** [comment]
@secabhi first you need to `return dialog.result`. Order of `.then` statements is important. Try this (put it right after `.open()`):

```
.catch((err: any) => console.log('ERROR: ' + err))
.then((dialog: any) => { return dialog.result })
.then((result: any) => { window.open('www.google.com','_blank') })
.catch((err: any) => { << put here something to handle cancel button or nothing if you dont need it >> });
```

**Comment by logar314159** [comment]
this is so anying and confusing, why is it done this way?

**Comment by Omar-IT** [comment]
Can anyone helpe me to fixe this issue: 'catch' does not exist on type 'DialogRef<TwoButtonPreset>'
openModal(video: any) {
    this.modal.prompt()
    .size('lg')
    .isBlocking(true)
    .showClose(true)
    .keyboard(27)
    .title('Ajouter à mes fovoris')
    .titleHtml('<h3>Ajouter cette vidéo à mes favoris</h3>')
    .body('Commentaire facultatif ("à voir demain", "montrer à Snoopy :)"...)')
    .bodyClass('modal-body')
    .footerClass('modal-footer')
    .okBtn('ajouter aux favoris')
    .okBtnClass('btn btn-primary')
    .open()
    .catch((err: any) => console.error(err)) // *******ERROR******************
    .then((dialog: any) => dialog.result)
    .then(result => this.modalOk(result, video))
    .catch(err => console.error(new Error('annulé par l\'utilisateur')));
  }
