### ISSUE TITLE
Error: Uncaught (in promise): No provider for ModalDialogInstance! (AdditionCalculateWindow -> ModalDialogInstance)

### ISSUE THREAD

**Issue by nikkwong** [shlomiassaf/angular2-modal#47]
```
Error: Uncaught (in promise): No provider for ModalDialogInstance! (AdditionCalculateWindow -> ModalDialogInstance)
```
Copied straight from the examples.

What's going on? 

Thx.

**Comment by shlomiassaf** [comment]
I can't really tell something from nothing.
You have to include what are you trying to do.

My best guess is that you're trying to use a custom modal in a wrong way, follow the example, it works, first make it work on your machine.

From there make changes and in the middle you'll see what you missed.

On the other hand, if its a bug, I can't reproduce it from this issue.

**Comment by allannienhuis** [comment]
I had to add providers: [Modal], to my @Component declaration.

    @Component({
      providers: [Modal],

      /* etc */
    })
    export class myComponent {}

I'm new to Angular2 so not sure yet why it's needed for this dependency and not for other dependencies in my component or in the demo app.
