### ISSUE TITLE
Replace existing dialog contentRef by another Component

### ISSUE THREAD

**Issue by NicolasCayet** [shlomiassaf/angular2-modal#48]
I'm working on a custom modal window, integrating a form. This form is composed of 4 parts, separated in 4 different components.
My goal is to keep the same dialog, which will return a single promise response to the opener component, and switch the dialog's contentRef to next form's component.

I achieved it by adding a getter on dialog's bootstrapRef property, then I execute the following TS code within my custom modal component:
```
    let bindings = Injector.resolve([
      provide(ModalDialogInstance, { useValue: this.dialog }),
      provide(ICustomModal, { useValue: this.modalContentData })
    ]);
    this.componentLoader.loadIntoLocation(
      this.modelContentData.nextFormType, this.dialog.bootstrapRef.location, 'modalDialog', bindings)
      .then(contentRef => {
        this.dialog.contentRef.dispose();
        this.dialog.contentRef = contentRef;
        return this.dialog;
      });
```

Firstly, do you see any issue doing this by this way ?
Secondly, what do you think about adding a getter on the bootstrapRef dialog's property ?

**Comment by shlomiassaf** [comment]
If I understand right, what you are trying to achieve is a "Wizard".

I believe the right approach for this is to have a main modal component which will be the only component sent to the modal service.

From there, the main modal will control the child components.

I believe this is the right approach and you will probably see angular 2 wizard components doing it this way (if not already exist).

The only issues you will have are:
 - Controlling the "ok" and "cancel" event so you can handle them and cancel/other logic
 - Controlling the "ok" and "cancel" text so they are bound to changed detection (currently not)

With there 2 options available you can change "ok" to "next" and control each next action, change the inner component you show and ofcourse change the text as you progress.

I'm working on supporting change detection for modal configuration like changing the button text, the header class, title, body etc...

As for the first, I will see when I can squeeze it.

What can you do now?

You can provide a component that implement both button's and inner component and add a class to the footer `footerClass` to hide it (`display: none` ?)

**Comment by shlomiassaf** [comment]
stale, closing...

**Comment by NicolasCayet** [comment]
I forgot to answer.
I finally load a "Layer" component within the modal dialog, which load the concrete component rendering my forms.

By the way, thank you for your involvement and for your module !

**Comment by tuanha** [comment]
89u8i
