### ISSUE TITLE
Miss index aggregating modules

### ISSUE THREAD

**Issue by mkjeff** [shlomiassaf/angular2-modal#52]
import * as modal from '**angular2-modal**'; // ts error: can't resolve

should add a index.ts aggregating module in the package

[packages_folder]/angular2-modal/index.ts
```ts
export * from './src/components/angular2-modal/index';
```

**Comment by shlomiassaf** [comment]
You can use this for now:

```ts
import * as modal from 'angular2-modal/angular2-modal';
```

![image](https://cloud.githubusercontent.com/assets/5377501/14475867/002a7c54-010d-11e6-9fcc-4a67eb1eb40d.png)
