### ISSUE TITLE
typescript can't find module

### ISSUE THREAD

**Issue by parol-peter** [shlomiassaf/angular2-modal#53]
After installing via NPM TypeScript compiler complains that it can't find "angular2-modal" module though modals work fine (systemjs dist js included in my index.html). 
after taking a look into angular's package and TS NPM compatibility section I think that some files are missing in your lib eg:
there is `node_modules/angular2/core.js` and  `node_modules/angular2/core.d.ts` that registers 'angular2/core' module so module name is reflecting package file path. TS resolves "global modules" like this "package/file" => "node_modules/package/file(.d).ts".

**The problem is that TS compiler doesn't know where to look for "angular2-modal" module.**

Of course I dont want to compile `angular2-modal.ts` into my app. I belive contents of this file should be in `angular2-modal.d.ts` plus compiled file `angular2-modal.js`. Then TSC would easily locate it by module name "angular2-modal/angular2-modal". Your module name should contain slash I reckon.

Best regards

**Comment by parol-peter** [comment]
renaming `angular2-modal.ts` file to `index.d.ts` in package root dir resolves the problem.

[www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html](https://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html)

**Comment by nbuso** [comment]
I have the same problem, from the link you suggested the algorithm is first looing package.json for the "typings" configuration and it's seem wrong.
In any case I tried renaming the file to "index.d.ts", i.e.:

```
$ ls node_modules/angular2-modal/
dist  index.d.ts  package.json  README.md
```
but
```
$ typings search angular2
No results found for search
```
am I missing something?

**Comment by parol-peter** [comment]
yeap. it seems **package.json is just wrong**
`"typings": "./dist/angular2-modal.d.ts",` should be `"typings": "dist/commonjs/angular2-modal.d.ts",`
after this slight change TS recognizes module name

`typing sreach` searches for typings available to install from public registries, doesn't it?
try command `typings search angular`

**Comment by shlomiassaf** [comment]
@parol-peter thanks, changed to you'r suggestion.
