### ISSUE TITLE
Iframe, would it be possible to popup in parent window?

### ISSUE THREAD

**Issue by ronencamera** [shlomiassaf/angular2-modal#58]

**Comment by shlomiassaf** [comment]
@ronencamera 
It should be possible.

You need to provide an IFrame Modal content component.
Look at the demo application for how I created the custom modal window.
This is the new modal content I created:
https://github.com/shlomiassaf/angular2-modal/blob/master/src/demo/app/customModalDemo/customModal.ts

And see how it is integrated into the code.

You can get data using the injected parameter.
