### ISSUE TITLE
Can not use NgClass in a modal window

### ISSUE THREAD

**Issue by erwin-beckers** [shlomiassaf/angular2-modal#6]
When you create a dialog and use ngClass in the template the following error is shown in the browser console: **EXCEPTION: No provider for IterableDiffers! (NgClass -> IterableDiffers)**

My component looks likes:

```javascript
import {Component} from "angular2/core";
import {CORE_DIRECTIVES} from "angular2/common";
import {ModalDialogInstance} from '../models/ModalDialogInstance';

@Component({
	selector: "modal-content",
	directives: [CORE_DIRECTIVES],
	template: `<div [ngClass]="{'myclass' : shouldUseMyClass}">hello</div>`
})
export class MyDialogComponent implements ICustomModalComponent
{
     public shouldUseMyClass: boolean=true;
     dialog: ModalDialogInstance;

    constructor(dialog: ModalDialogInstance, modelContentData: ICustomModal) {
       ...
   }
}

```

**Comment by shlomiassaf** [comment]
AFAIK its an angular bug.

See angular/angular#4330 for more details and a temp workaround.

**Comment by erwin-beckers** [comment]
Thanks for your quick reply. Do you have an example how to do the work around ?

**Comment by shlomiassaf** [comment]
Try calling the `open` or `openInside` methods of the Modal service with a resolved binding of IterableDiffers

Assuming we are in a random component, lets says the component of a page which has a function thats opens the dialog.

```
@Component({
    selector: 'demo-page', 
    providers: [Modal],
    template: require('./demoPage.tpl.html')
})
export class DemoPage {
    constructor(private modal: Modal, private element: ElementRef, private injector: Injector) {
    }

    openDialog() {
        let bindings = this.injector.get(IterableDiffers);
        this.modal.open(this.element, bindings);
    }
}
```

Didn't test it, but I hope it works, let me know...

**Comment by shlomiassaf** [comment]
Added example how to workaround this issue, see readme.me for more details or review the [commit](https://github.com/shlomiassaf/angular2-modal/commit/22497b67dff6f087fe235653b3f1564fe2fe50d8)
