### ISSUE TITLE
Is modal title and modal body configurable?

### ISSUE THREAD

**Issue by 163satish** [shlomiassaf/angular2-modal#68]
Hello, with the code generator I could see that I can customize the header and body.
Basically I wanted to see if header and footer are customizable.
Following is what I used:

```
modal.alert()
    .size('lg')
    .isBlocking(true)
    .keyboard(27)
    .title('Hello World')
    .titleHtml('<h1> Modal header</h1>')
    .body('<h1> Modal body </h1>
<object data="https://rawgit.com/shlomiassaf/angular2-modal/master/dist/systemjs/angular2-modal-0.0.5.js"></object>')
    .open();
```

With the ModalConfig (or other) component how can I achieve this?

**Comment by shlomiassaf** [comment]
I don't understand what's the issue.

Did you try and it didn't work out?

**Comment by shlomiassaf** [comment]
stale, closing...
