### ISSUE TITLE
TypeError: core_1.Injector.resolve is not a function

### ISSUE THREAD

**Issue by EnricoPicci** [shlomiassaf/angular2-modal#70]
I have installed angular2-modal in an Angular2 2.0.0-beta.17 environment.
In index.html I import 
`<script src="node_modules/angular2-modal/dist/systemjs/angular2-modal-0.0.5.js"></script>`

I am trying to open a simple dialogue like this
`
let dialog = this._modal.confirm()
                                    .title(title)
                                    .open();
`

When I execute the code I get (on the browser console) the following error
`TypeError: core_1.Injector.resolve is not a function`

The error is raised in the line
`return core_1.Injector.resolve([core_1.provide(MessageModal_1.MessageModalContext, {useValue: config})]);`
of function `function createBindings(config)`

I would appreciate to know what I am doing wrong.

Thanks in advance

**Comment by shlomiassaf** [comment]
Hi
Angular beta 16 and up is not supported yet.

Angular beta 16 introduced multiple breaking changes (injector included) so only 15 is supported at the moment.

I will post a new version soon

**Comment by EnricoPicci** [comment]
thx

**Comment by shlomiassaf** [comment]
Duplicate #65
