### ISSUE TITLE
No provider for DialogRef when using SystemJS

### ISSUE THREAD

**Issue by CaselIT** [shlomiassaf/angular2-modal#79]
I'm testing the version 1, but I cannot load a custom component as a dialog when using systemjs.
Here I'm trying to load Test as dialog:
```ts
import { Component, ViewContainerRef } from '@angular/core';
import { Modal, BS_MODAL_PROVIDERS, BSModalContext } from 'angular2-modal/plugins/bootstrap/index';
import { ModalComponent, DialogRef } from 'angular2-modal';
import {MODAL_BROWSER_PROVIDERS} from 'angular2-modal/platform-browser/index';
import { bootstrap } from '@angular/platform-browser-dynamic';
@Component({
  selector: 'app',
  template: `<div class="well"><label>Modal test</label><br><div class="btn-group" role="group"><button class="btn btn-default" (click)='test()'>custom component</button>    </div></div>`,
  providers: [BS_MODAL_PROVIDERS]
})
export class App {
  constructor(public modal: Modal, viewContainer: ViewContainerRef) {
    modal.defaultViewContainer = viewContainer;
  }
  test() { 
    this.modal.open(Test, new AdditionCalculateWindowData(2, 3))
  }
}
export class AdditionCalculateWindowData extends BSModalContext {
  constructor(public num1: number, public num2: number) {
    super();
  }
}
@Component({
  selector: 'modal-content',
  template: 'Test!'
})
export class Test implements ModalComponent<AdditionCalculateWindowData>  {
  constructor(public dialog: DialogRef<AdditionCalculateWindowData>) {
  }
}
bootstrap(App, [MODAL_BROWSER_PROVIDERS]);
```
But I get the error `ORIGINAL EXCEPTION: No provider for DialogRef!`

The systemjs configuration I've used to load angular2-modal is:
```js
System.config({ 
  packages: { 'angular2-modal': { defaultExtension: 'js', main: 'index.js' }
  map:{ 'angular2-modal': 'node_modules/angular2-modal/' }
})
```

Am I doing something wrong?

**Comment by CaselIT** [comment]
@shlomiassaf I've found the issue. It appears that angular considers `DialogRef` two different types based on where it is exported. 
I've changed the import of  `DialogRef` from `import { DialogRef } from 'angular2-modal';` to `import { DialogRef } from 'angular2-modal/models/dialog-ref';` and is now working correctly.

**Comment by shlomiassaf** [comment]
I'll take a look when i come back from my vacation

**Comment by shlomiassaf** [comment]
The commit removes all exports from the barrels (angular2-modal and angular2-modal.all)

One will have to import `DialogRef` using a direct path, this is not a desired behaviour.
On top of that, a UMD build will break since DialogRef will by unreachable.

I suspect it might be a wrong SystemJS configuration perhaps?

Take a look at the demo, there isn't any issue with DialogRef there.
Also, DialogRef is exported in a barrel, with other exports as well so why only DialogRef has an issue?

**Comment by CaselIT** [comment]
I don't think its a systemjs problem since it can load all the files.
In any case I've tried the same configuration used in the example but I get the same error.
```js
System.config({ 
  packages: { 
   'angular2-modal': { defaultExtension: 'js', main: 'index.js' },
   'angular2-modal/platform-browser': { main: 'index.js', defaultExtension: 'js' },
   'angular2-modal/plugins/bootstrap': { main: 'index.js', defaultExtension: 'js' },
   'angular2-modal/plugins/vex': {main: 'index.js', defaultExtension: 'js'},
   'angular2-modal/plugins/js-native': {main: 'index.js', defaultExtension: 'js'}
  },
  map:{ 'angular2-modal': 'node_modules/angular2-modal/' }
})
```

Debugging the problem occurs when loading the `Test` instance, `BSModalBackdrop` constructor runs and has the correct dialog instance. The problem seems to be that `DialogRef` in imported from two different places.

Regarding the PR was just a way to avoid the wrong import for the `DialogRef`. I'll close it since it's not compatible with UMD.

**Comment by shlomiassaf** [comment]
The best thing is to setup a proper SystemJS demo in plunker.

I will have to provide a proper UMD bundle for that.... so I'll work on that.

**Comment by CaselIT** [comment]
I could share a repo in the meantime.
>Also, DialogRef is exported in a barrel, with other exports as well so why only DialogRef has an issue?

I think the problem is in the Dependency Injection. Only DialogRef is injected in the modal

**Comment by CaselIT** [comment]
I've put an example in this repo
https://github.com/CaselIT/angular2-modal-dialogref-error

To start it just use `npm` i then `npm start`

**Comment by shlomiassaf** [comment]
@CaselIT Every passing day I hate SystemJS more and more and more...
This is the most time consuming piece of engineering I have ever seen, really!

Anyway, I still didn't solve the issue, I don't know if the origin is my code or your code but this is what I found:
![image](https://cloud.githubusercontent.com/assets/5377501/15338659/84c6825e-1c89-11e6-8c00-3bbbfe517ab5.png)

Notice that every source file has **2** JS files for the same name?
If you put a break point at each (JS, not TS) you will see it hit's twice.
It actually creates 2 different objects for every exported item in a duplicated file.
Note that it happens in the `models` directory and `framework`, most others are fine.

So basically what I think happens is that in the config when you map:
```
 'angular2-modal': 'node_modules/angular2-modal/',
 'angular2-modal/platform-browser': 'node_modules/angular2-modal/platform-browser'
```

It actually does the 2nd line as if the 1st line never existed having 2 copies of runtime for every object that is both imported in line 1 and in line 2.

If you go to the [demo](http://shlomiassaf.github.io/angular2-modal/) which is also running SystemJS you won't see such a thing, it has only 1 file per source.

I don't know if its SystemJS, my code, the lite-server or what ever but I just wasted 3 hours on it, this is why I hate systemJS and why I think choosing it for angular as a demo core is the worst thing every...
I understand why, it's the way things will look in the future, but man its a piece of ****

**Comment by CaselIT** [comment]
I agree that SystemJS is quite strange at times.
In any case I've the same problem even serving the site with express with `servestatic`, so it should not be `liteserver`.
What is even stranger is that I've just checked and in the configuration I map the library only [once](https://github.com/CaselIT/angular2-modal-dialogref-error/blob/master/system.config.js#L48)

**Comment by CaselIT** [comment]
Ok I just fixed this bug...
The fault was the tailing `/` in the map......
Changing from `'angular2-modal': 'node_modules/angular2-modal/'` to `'angular2-modal': 'node_modules/angular2-modal'` fixes the double file problem and the issue. It seems that it loaded the file twice once as `http://localhost:3000/node_modules/angular2-modal/framework/...` and once as `http://localhost:3000/node_modules/angular2-modal//framework/...`.
I've updated the repo.
Sorry to have wasted your time for such a thing. :disappointed: 
Do you think that it is reasonable to file an issue on SystemJS ?

**Comment by shlomiassaf** [comment]
no problem, I'v learned something new and reduced future head banging, monitor breaking hours 👍 

I don't know, you can try they might know about this already, there might be a config for trailing slashes like they had in `angular 1` with `angular-resource`:  
`$resourceProvider.defaults.stripTrailingSlashes = false;`

Anyway, thanks :)

**Comment by CaselIT** [comment]
Thanks to you also for this library. :+1: 

I'll close this now.
