### ISSUE TITLE
Publish at npm

### ISSUE THREAD

**Issue by haoliangyu** [shlomiassaf/angular2-modal#8]
The modal window is awesome. Could it be published at npm?

**Comment by shlomiassaf** [comment]
I will have to restructure parts of the code, add `.npmignore` and configure webpack to make a build for the component only (right now it also compiles the demo site as well)

Since angular is still in beta I dont know how much it will help but I will work on it.

**Comment by shlomiassaf** [comment]
Please try to use it as a package
```
    npm install angular2-modal --save
```

I would like to know if it worked.

**Comment by gkochakidze** [comment]
+. worked perfectly

**Comment by haoliangyu** [comment]
@shlomiassaf Thanks for publishing this awesome package and @gkochakidze thanks for testing :)
