### ISSUE TITLE
MODAL_PROVIDERS is undefined

### ISSUE THREAD

**Issue by AndreyKotofotoff** [shlomiassaf/angular2-modal#80]
Hello.
ts:
`import {Modal, MODAL_PROVIDERS} from 'angular2-modal';`

systemjs.config
`'angular2-modal': '/js/angular2-modal.0.1.7.js'` (copy from node_modules/dist/systemjs)

**Comment by shlomiassaf** [comment]
This is the old version.

New version does not have 1 UMD bundle, you need to apply system JS configuration.

See the demo app (index.SystemJS.html)
