### ISSUE TITLE
Dependecy injection in custom component's constructor

### ISSUE THREAD

**Issue by xxccdef** [shlomiassaf/angular2-modal#82]
I would like to use custom component for my modal with several dependencies defined in component's constructor. I believe I must pass `bindings: ResolvedReflectiveProvider[]` to `modal.open` as third parameter but I'm not familiar with angular2 injector internals and especially how to construct this `ResolvedReflectiveProvider[]` parameter.

Anyone could provide any hints?

My modal component looks like this:

```
export class ImageBrowserModal {
    
    constructor(private ref: DialogRef<any>, private imageService: ImageService) {  }
    
}
```

If I remove `ImageService` from constructor, modal opens just fine. Otherwise I get this error:

```
EXCEPTION: Error: Uncaught (in promise): TypeError: Cannot read property 'query' of null
```

**Comment by xxccdef** [comment]
Apparently I needed to use `ReflectiveInjector` from `@angular/core`:


```
 let bindings = ReflectiveInjector.resolve([
    ImageService
]);
this.modal.open(ImageBrowserModal, {}, bindings);
```

**Comment by AbdulRahmanAlHamali** [comment]
Hello,

I tried the solution, but it is still failing for me, and it is failing without showing any error. The backdrop does show, but then the dialog does not. 

Any idea on what I can do?

@shlomiassaf
