### ISSUE TITLE
 Property does not exist on type 'ModalControllingContextBuilder<any>'

### ISSUE THREAD

**Issue by karnex47** [shlomiassaf/angular2-modal#85]
When calling any method (other than open) on modal.alert() (like size, body etc.), it complains with following error:
 Property 'size' does not exist on type 'ModalControllingContextBuilder<any>

It doesn't stop the dev build, but its breaking prod build. I am using angular2-webpack starter and bootstrap modal. Let me know if you need any more info

**Comment by shlomiassaf** [comment]
It doesn't happen in the demo which is angular 2 + webpack.

Are you extending something?

**Comment by karnex47** [comment]
It was my mistake. Instead of importing modal from plugins/bootstrap, I imported from angular2-modal/angular2-modal. Closing the issue.

**Comment by shlomiassaf** [comment]
Not sure it's not a big, or at least an issue that might cause confusion, I'll want to think about this

**Comment by MartinNuc** [comment]
I got trapped in this too. Webstorm suggests `angular2-modal/angular2-modal` as default import. Using `import {Modal} from "angular2-modal/plugins/bootstrap/modal";` helped.

**Comment by shlomiassaf** [comment]
@MartinNuc Webstorm auto **import** suggestions are not optimal at this point, sometimes it hits sometimes it gets a crazy result...

I every time I TAB on auto complete for a type I scroll up to check...

**Comment by shlomiassaf** [comment]
I'll close this stale issue, please re-open with a comment if it still an issue.
