### ISSUE TITLE
Use component in modal body

### ISSUE THREAD

**Issue by LeResKP** [shlomiassaf/angular2-modal#88]
Hello, is there any way to use a component in the modal body ? 
For my case, I want to get the modal content asynchroniously. I didn't find anything in the doc and I just gave a try without success. 
Also I need to have form in the modal and It seems the body content is not parsed in angular, is it right ?
Thks

**Comment by tlorenzetti** [comment]
I guess you need to create a custom modal (like in the [demo sample](https://github.com/shlomiassaf/angular2-modal/blob/master/src/demo/app/bootstrap-demo/bootstrap-demo-page/custom-modal-sample.ts)) to use your component. I did so and it works fine.

**Comment by shlomiassaf** [comment]
Hi,

See [here](https://github.com/shlomiassaf/angular2-modal/blob/master/src/demo/app/bootstrap-demo/bootstrap-demo-page/bootstrap-demo-page.ts#L51-L53)
You provide a type (component class)

**Comment by LeResKP** [comment]
Thank you @tlorenzetti and @shlomiassaf , I will give a try!
